### ISSUE TITLE
Unable to play tile-based hevc video with muti-representations

### ISSUE THREAD

**Issue by ForgetMe17** [gpac/gpac#1491]
Hi community:

While i am using MP4Client(build on `filters` branch) to play mpd file which contains two representations(bit rates 256k and 48k). The player has a black screen and the terminal does not have any warnings or errors.

I have followed the instrutions on [https://github.com/gpac/gpac/wiki/Tiled-Streaming](https://github.com/gpac/gpac/wiki/Tiled-Streaming).
I created two versions of video, their bit rates are 256k and 48k:
`kvazaar -i BestVR.yuv --input-res 1280x720 -o BestVR-48k.hvc --tiles 3x3 --slices tiles --mv-constraint frametilemargin --bitrate 48000`
`kvazaar -i BestVR.yuv --input-res 1280x720 -o BestVR-256k.hvc --tiles 3x3 --slices tiles --mv-constraint frametilemargin --bitrate 256000`
Then i use MP4Box(build on `filters` branch) to split tiles:
`MP4Box -add BestVR-48k.hvc:split_tiles -fps 30 -new BestVR-tiled-48k.mp4`
`MP4Box -add BestVR-256k.hvc:split_tiles -fps 30 -new BestVR-tiled-256k.mp4`
Then to generate MPD file:
`MP4Box -dash 3000 -rap -frag-rap -profile live -out BestVR.mpd ../BestVR-tiled-256k.mp4 ../BestVR-tiled-48k.mp4`

While i am using the MP4Client, i got a black screen:
`MP4Client BestVR.mpd`

I log the dash@bebug, attached are the log file.
[bestvr.log](https://github.com/gpac/gpac/files/4643320/bestvr.log)

Appreciate for any help on this issue.

**Comment by eric3120925** [comment]
I got the same problem on MP4Cleint (filters branch).

It could play the tiled-based video well on v0.8.0. 
But when I try to change the bitrate on single tile, the player turn to black screen and stop playing.
Is anyone know how to solve it?

**Comment by jeanlf** [comment]
we had an issue in filters on dashing multiple tiled inputs, this should now be fixed ([test added](https://github.com/gpac/testsuite/blob/filters/scripts/dash-srd-hevc.sh)). Could you check if that solves your issue ?

**Comment by eric3120925** [comment]
I still can't use tile adaptation on both filters and v0.8.0 MP4Client.
The steps of creating videos and MPD file were likely same as @ForgetMe17 did, but i used 4K videos.
I checked the log dash@info and found that when I tried to set the quality of tiles, MP4Client would request  the file which not on the server and stop playing.

[HTTP] Failure: <!DOCTYPE HTML PUBLIC "-//IETF//DTD HTML 2.0//EN">
<html><head>
<title>404 Not Found</title>
</head><body>
<h1>Not Found</h1>
<p>The requested URL was not found on this server.</p>
<hr>
<address>Apache/2.4.18 (Ubuntu) Server at 192.168.0.15 Port 80</address>
</body></html>

[HTTP] Error parsing reply: Requested URL is not valid or cannot be found for URL http://192.168.0.15/h30+12/h_12_dash_track1_125.m4s
Reply was:
HTTP/1.1 404 Not Found
Date: Fri, 29 May 2020 07:16:46 GMT
Server: Apache/2.4.18 (Ubuntu)
Content-Length: 274
Keep-Alive: timeout=5, max=11
Connection: Keep-Alive
Content-Type: text/html; charset=iso-8859-1

[DASH] Failed to download http://192.168.0.15/h30+12/h_12_dash_track1_125.m4s = Requested URL is not valid or cannot be found...


[DASH] Error in downloading new segment: http://192.168.0.15/h30+12/h_12_dash_track1_125.m4s Requested URL is not valid or cannot be found - starting countdown for 1000 ms


[dashLogs.log](https://github.com/gpac/gpac/files/4700266/dashLogs.log)

I will be grateful for any help.

**Comment by eric3120925** [comment]
Hey
I found that using MP4Box to re-create the tile video (tile_q1.mp4, tile_q2mp4) and generate the MPD file ,then dashing them on MP4Client(v0.9.0) was worked !!

But I could only see the option of adjusting the quality of the base layer and couldn't see the option on other tile.

Is there any configuration that need to change on GPAC.cfg(v0.9.0) or something that I don't know? 

![圖片](https://user-images.githubusercontent.com/37995728/83534976-13558980-a524-11ea-8c33-57575437bb29.png)

**Comment by ForgetMe17** [comment]
Yes, on branch v0.9.0 it works.
I am using gpac dashin:tile_mode=center to control tiles.

**Comment by eric3120925** [comment]
> 
> 
> Yes, on branch v0.9.0 it works.
> I am using gpac dashin:tile_mode=center to control tiles.

I tried to set **dashin:tile_mode=center** in v0.9.0 but still couldn't control tiles.

I also found that I couldn't change the quality of the video.
The quality setting button didn't work.
![圖片](https://user-images.githubusercontent.com/37995728/84471295-a2e30100-acb7-11ea-95a3-a559caa4667b.png)


@ForgetMe17 Could you send me the MPD file and the video?

**Comment by ForgetMe17** [comment]
Hi @eric3120925 . I am using the following command:
`gpac httpin:src=http://localhost/vrtile/BestVR.mpd dashin:tile_mode=rows:start_with=max_bw tileagg compositor vout`
This is the output:
![image](https://user-images.githubusercontent.com/32082049/84588926-eaa38d00-ae5d-11ea-8d65-e3285a0536e2.png)
The quality of the first row is much higher than the rest rows, so it seems possible to render tiles in different quality for 360 video in the latest version of v0.9.0.
If you are testing on a local file use:
`gpac -src vrtile/dash-mutirep/BestVR.mpd dashin:tile_mode=center:start_with=max_bw mp4dmx tileagg compositor vout` should work.
I am now figuring out how to enable quality adaption since the above command only results in a constant quality which will not change during the play. I am hoping it can be changed according to the bandwith or possible some other signals like the gaze info.
@jeanlf can the quality of tiles be changed according to the gaze infomation, like we just take where the mouse cursor points at as the gaze area?

**Comment by ForgetMe17** [comment]
In [src/media_tools/dash_client.c](https://github.com/gpac/gpac/blob/filters/src/media_tools/dash_client.c)
From line 3437 to 3457
```
/* Call a specific adaptation algorithm (see GPAC configuration)
	Each algorithm should:
	- return the new_index value to the desired quality

	It can use:
	- the information about each available representation (group->adaptation_set->representations, e.g. bandwidth required for that representation)
	- the information of the current representation (rep)
	- the download_rate dl_rate (computed on the previously downloaded segment, and adjusted to the playback speed),
	- the buffer levels:
	    - current: group->buffer_occupancy_ms,
		- previous: group->buffer_occupancy_at_last_seg
		- max: group->buffer_max_ms,
	- the playback speed,
	- the maximum achievable speed at the current resolution,
	- the indicator that the current representation is too demanding CPU-wise (force_lower_complexity)

	Private algorithm information should be stored in the dash object if global to all AdaptationSets,
	or in the group if local to an AdaptationSet.

	TODO: document how to access other possible parameters (e.g. segment sizes if available, ...)
	*/
```
This is function available now, if so, how can i add my own adaptation algorithm, and make configs to make this algorithm applied?
Appreciate for your advice! @jeanlf

**Comment by eric3120925** [comment]
> 
> 
> Hi @eric3120925 . I am using the following command:
> `gpac httpin:src=http://localhost/vrtile/BestVR.mpd dashin:tile_mode=rows:start_with=max_bw tileagg compositor vout`
> 
> This is the output:
> ![image](https://user-images.githubusercontent.com/32082049/84588926-eaa38d00-ae5d-11ea-8d65-e3285a0536e2.png)
> The quality of the first row is much higher than the rest rows, so it seems possible to render tiles in different quality for 360 video in the latest version of v0.9.0.
> 
> If you are testing on a local file use:
> `gpac -src vrtile/dash-mutirep/BestVR.mpd dashin:tile_mode=center:start_with=max_bw mp4dmx tileagg compositor vout` should work.
> 
> I am now figuring out how to enable quality adaption since the above command only results in a constant quality which will not change during the play. I am hoping it can be changed according to the bandwith or possible some other signals like the gaze info.
> 
> @jeanlf can the quality of tiles be changed according to the gaze infomation, like we just take where the mouse cursor points at as the gaze area?

Hey @ForgetMe17, your suggestion helps me a lot!! Thanks!!

**Comment by ForgetMe17** [comment]
@jeanlf can the quality of tiles be changed according to the gaze infomation, like we just take where the mouse cursor points at as the gaze area?

**Comment by eric3120925** [comment]
@ForgetMe17 I have the same problem about using gaze information to change tiles quality.
I found that when add a function in "dash_client.c": 
"gf_dash_set_tiles_quality(dash, a_group->srd_desc);"

`
GF_EXPORT
GF_Err gf_dash_group_set_visible_rect(GF_DashClient *dash, u32 idx, u32 min_x, u32 max_x, u32 min_y, u32 max_y, Bool is_gaze)
{
	u32 i, count;
	GF_DASH_Group *group = gf_list_get(dash->groups, idx);
	if (!group) return GF_BAD_PARAM;

	if (!min_x && !max_x && !min_y && !max_y) {
		group->quality_degradation_hint = 0;
	}


	//TODO - single video, we may want to switch down quality if not a lot of the video is visible
	//we will need the zoom factor as well
	if (!group->groups_depending_on) return GF_OK;

	GF_LOG(GF_LOG_DEBUG, GF_LOG_DASH, ("[DASH] Group Visible rect %d,%d,%d,%d \n", min_x, max_x, min_y, max_y));
	count = gf_list_count(group->groups_depending_on);
	for (i=0; i<count; i++) {
		Bool is_visible = GF_TRUE;
		GF_DASH_Group *a_group = gf_list_get(group->groups_depending_on, i);
		if (!a_group->srd_w || !a_group->srd_h) continue;

		if (is_gaze) {

			if (min_x < a_group->srd_x)
				is_visible = GF_FALSE;
			else if (min_x > a_group->srd_x + a_group->srd_w)
				is_visible = GF_FALSE;
			else if (min_y < a_group->srd_y)
				is_visible = GF_FALSE;
			else if (min_y > a_group->srd_y + a_group->srd_h)
				is_visible = GF_FALSE;

		} else {

			//single rectangle case
			if (min_x<max_x) {
				if (a_group->srd_x+a_group->srd_w <min_x) is_visible = GF_FALSE;
				else if (a_group->srd_x>max_x) is_visible = GF_FALSE;
			} else {
				if ( (a_group->srd_x>max_x) && (a_group->srd_x+a_group->srd_w<min_x)) is_visible = GF_FALSE;
			}

			if (a_group->srd_y>max_y) is_visible = GF_FALSE;
			else if (a_group->srd_y+a_group->srd_h < min_y) is_visible = GF_FALSE;

		}

		a_group->quality_degradation_hint = is_visible ? 0 : 100;
		gf_dash_set_tiles_quality(dash, a_group->srd_desc);
		GF_LOG(GF_LOG_DEBUG, GF_LOG_DASH, ("[DASH] Group SRD %d,%d,%d,%d is %s\n", a_group->srd_x, a_group->srd_w, a_group->srd_y, a_group->srd_h, is_visible ? "visible" : "hidden"));
	}
	return GF_OK;
}
` 
It makes the quality of initial FOV tiles be high quality, then else tiles are low quality.
![圖片](https://user-images.githubusercontent.com/37995728/85982774-fb84fe80-ba18-11ea-8b80-6e9f7eb47dc7.png)
![圖片](https://user-images.githubusercontent.com/37995728/85984434-c3cb8600-ba1b-11ea-91f8-15f1ffdfeb1b.png)


But when I tried to move FOV to another position, the tiles of old FOV became low quality, and the tiles of new FOV didn't  change to high quality (they still were low quality).
![圖片](https://user-images.githubusercontent.com/37995728/85983417-13a94d80-ba1a-11ea-9258-7e15d8865998.png)

I think I need to spend some time to know how to use the function.

**Comment by eric3120925** [comment]
I think I figure out how to adapt the quality of tiles based on FOV according the gaze info.
In addition to editing the function above `GF_Err gf_dash_group_set_visible_rect` , 
I also edit `static void gf_dash_set_tiles_quality`

`static void gf_dash_set_tiles_quality(GF_DashClient *dash, struct _dash_srd_desc *srd)
{
	u32 i, count;
	Bool tiles_use_lowest = (dash->first_select_mode==GF_DASH_SELECT_BANDWIDTH_HIGHEST_TILES) ? GF_TRUE : GF_FALSE;

	count = gf_list_count(dash->groups);
	for (i=0; i<count; i++) {
		GF_DASH_Group *group = gf_list_get(dash->groups, i);
		u32 lower_quality;
                gf_dash_set_group_representation(group,
		                                 gf_list_last(group->adaptation_set->representations)); // change to highest quality for tiles in FOV
		if (group->srd_desc != srd) continue;

		lower_quality = gf_dash_get_tiles_quality_rank(dash, group);
		if (!lower_quality) continue;

		if (tiles_use_lowest && (group->active_rep_index >= lower_quality)) {
			lower_quality = group->active_rep_index - lower_quality;
		} else {
			lower_quality = 0;
		}
		gf_dash_set_group_representation(group,
		                                 gf_list_get(group->adaptation_set->representations, lower_quality) ); 
	}
}`

When I move the FOV, the tiles in FOV will stay in high quality and the tiles out of FOV will change to low quality.
I checked the dash log `dash@debug` and I found that the player would change quality twice for tiles out of FOV.
In the beginning the tile would set to high quality, then change to low quality if it wasn't in FOV.
I think there is some space for improvement of efficiency.

**Comment by ForgetMe17** [comment]
@eric3120925 Wow, this looks awesome! Thanks for sharing.
How do you change the FOV in the player? I tried the keyboard and mouse grab, but none of them worked.

**Comment by eric3120925** [comment]
I use this command:
`MP4Client -i your video URL#VR --sgaze=true`
The player enables the gaze info by using  `--sgaze=true` , and it needs to be in VR mode.
Because I don't know how to start in VR mode by `gpac` command, I use command `MP4Client` for replacing.

**Comment by jeanlf** [comment]
Nice thread guys, I need to turn that into a [howto](https://github.com/gpac/gpac/wiki/Howtos) entry!

> Because I don't know how to start in VR mode by gpac command,  

There is a default alias `-gui`for this, see `gpac -h` `gpac -gui -h`. Launching in VR would be `gpac -gui URL#VR`.

__WARNING__  
the gpac app uses by default no threads, only the main process, while MP4Client uses by default 2 additional threads. So to be strictly equivalent, use `gpac -threads=2 -gui URL#VR` (or edit the gui alias).

> In the beginning the tile would set to high quality, then change to low quality if it wasn't in FOV

Does this happen when you set `--start_with=min_q` (start everything in the dash session in low quality) ? If so we have a bug

We likely have room for improvement on fov selection, both in the rate selection algo and in visualization help. For instance I'd like to have `--tvtd` applicable somehow when merging tiles, so that low quality tiles can be skipped in the merge process. We also need to plug in [hevcmerge](https://github.com/gpac/gpac/wiki/hevcmerge) for cases where tiles were rewritten as standalone HEVC streams.

I'm leaving this open until we add an entry in the howto section.

**Comment by ForgetMe17** [comment]
Hi @eric3120925 , have you met the `Buffering` problem? While i am play a 5x5 tiled video, it got stuck saying that it is buffering.
![1](https://user-images.githubusercontent.com/32082049/89158354-8ae57a80-d5a0-11ea-8b9b-26b18eee1c1c.png)

The player just paused here and have no response. I think this maybe a hardware issue.

**Comment by eric3120925** [comment]
> There is a default alias -guifor this, see gpac -h gpac -gui -h. Launching in VR would be gpac -gui URL#VR.
@jeanlf Thank you for the command.

> Does this happen when you set --start_with=min_q (start everything in the dash session in low quality) ?
When I set `--start_with=min_q`, the player will not start everything in the dash session in low quality.
I think that's because I edit the functions `gf_dash_set_tiles_quality` and `gf_dash_group_set_visible_rect` for making the tiles in FOV stay in high quality, then tiles out of FOV become low quality.

@ForgetMe17 Yes, I did met this buffering problem.
When I tried to play 8x8 tiled video, the player would totally get stuck.
Then I tried the 6x6 tiled video, the video could be played.
But when I didn't move the FOV, it got stuck for buffering the new video session sometimes.
If I tried to move the FOV, it took more time for buffering.

In 6x6, it can be played eventually, not like in 8x8, that will totally get stuck.
So I think it is a hardware issue.

**Comment by chitragupt** [comment]
> Hi @eric3120925 , have you met the `Buffering` problem? While i am play a 5x5 tiled video, it got stuck saying that it is buffering.
> ![1](https://user-images.githubusercontent.com/32082049/89158354-8ae57a80-d5a0-11ea-8b9b-26b18eee1c1c.png)
> 
> The player just paused here and have no response. I think this maybe a hardware issue.

I'm having this same issue while I'm trying to stream tears of steel mpd provided on wiki page.Earlier I have tried streaming the same mpd using mp4client and it worked.Have you found any solution ?

**Comment by eric3120925** [comment]
I figure out the solution by adding the check value `u32 check_v = a_group->quality_degradation_hint`.
And I put `if(check_v == a_group->quality_degradation_hint) continue` before setting the new quality `gf_dash_set_tiles_quality(dash,a_group->srd_desc)`.

This way makes tiles setting new quality when the value of **quality_degradation_hint** change (This means some tiles get out of the FOV, and some of them get in the FOV.)

So, if the value of **quality_degradation_hint** of the tile doesn't change, `if(check_v == a_group->quality_degradation_hint) continue` will skip the function `gf_dash_set_tiles_quality(dash,a_group->srd_desc)` , then keeps the same downloading sequence and checks the next tile.

This greatly increases performance of the player when moving the FOV.
Because every time executing the function `gf_dash_set_tiles_quality(dash,a_group->srd_desc)` will reset the quality of all tiles of the video.
If there are 6x6 tiles of the video, the function `GF_Err gf_dash_group_set_visible_rect` will check one tile at a time whether in the FOV or not, and each time it will execute the function `gf_dash_set_tiles_quality(dash,a_group->srd_desc)`.
We can discover that a tile will reset the quality of 36 tiles, and there are 36 tiles, this makes 36 * 36 times resetting.
I think this is the reason of `Buffing` problem when moving the FOV.

```
for (i=0; i<count; i++) {
		Bool is_visible = GF_TRUE;
		GF_DASH_Group *a_group = gf_list_get(group->groups_depending_on, i);
                **u32 check_v = a_group->quality_degradation_hint;**
		if (!a_group->srd_w || !a_group->srd_h) continue;

		if (is_gaze) {

			if (min_x < a_group->srd_x)
				is_visible = GF_FALSE;
			else if (min_x > a_group->srd_x + a_group->srd_w)
				is_visible = GF_FALSE;
			else if (min_y < a_group->srd_y)
				is_visible = GF_FALSE;
			else if (min_y > a_group->srd_y + a_group->srd_h)
				is_visible = GF_FALSE;
		} else {

			//single rectangle case
			if (min_x<max_x) {
				if (a_group->srd_x+a_group->srd_w <min_x) is_visible = GF_FALSE;
				else if (a_group->srd_x>max_x) is_visible = GF_FALSE;
			} else {
				if ( (a_group->srd_x>max_x) && (a_group->srd_x+a_group->srd_w<min_x)) is_visible = GF_FALSE;
			}

			if (a_group->srd_y>max_y) is_visible = GF_FALSE;
			else if (a_group->srd_y+a_group->srd_h < min_y) is_visible = GF_FALSE;

		}
		a_group->quality_degradation_hint = is_visible ? 0 : 100;
		
		//printf("(%d , %d) is %s \n", a_group->srd_row_idx, a_group->srd_col_idx, is_visible ? "visible" : "hidden");
		GF_LOG(GF_LOG_DEBUG, GF_LOG_DASH, ("[DASH] Group SRD %d,%d,%d,%d is %s\n", a_group->srd_x, a_group->srd_w, a_group->srd_y, a_group->srd_h, is_visible ? "visible" : "hidden"));
                **if(check_v == a_group->quality_degradation_hint) continue;**
                gf_dash_set_tiles_quality(dash,a_group->srd_desc);
	}
```

**Comment by LouHan-0325** [comment]
> I figure out the solution by adding the check value `u32 check_v = a_group->quality_degradation_hint`.
> And I put `if(check_v == a_group->quality_degradation_hint) continue` before setting the new quality `gf_dash_set_tiles_quality(dash,a_group->srd_desc)`.
> 
> This way makes tiles setting new quality when the value of **quality_degradation_hint** change (This means some tiles get out of the FOV, and some of them get in the FOV.)
> 
> So, if the value of **quality_degradation_hint** of the tile doesn't change, `if(check_v == a_group->quality_degradation_hint) continue` will skip the function `gf_dash_set_tiles_quality(dash,a_group->srd_desc)` , then keeps the same downloading sequence and checks the next tile.
> This greatly increases performance of the player when moving the FOV.
> 
> Because every time executing the function `gf_dash_set_tiles_quality(dash,a_group->srd_desc)` will reset the quality of all tiles of the video.
> If there are 6x6 tiles of the video, the function `GF_Err gf_dash_group_set_visible_rect` will check one tile at a time whether in the FOV or not, and each time it will execute the function `gf_dash_set_tiles_quality(dash,a_group->srd_desc)`.
> We can discover that a tile will reset the quality of 36 tiles, and there are 36 tiles, this makes 36 * 36 times resetting.
> I think this is the reason of `Buffing` problem when moving the FOV.
> 
> ```
> for (i=0; i<count; i++) {
> 		Bool is_visible = GF_TRUE;
> 		GF_DASH_Group *a_group = gf_list_get(group->groups_depending_on, i);
>                 **u32 check_v = a_group->quality_degradation_hint;**
> 		if (!a_group->srd_w || !a_group->srd_h) continue;
> 
> 		if (is_gaze) {
> 
> 			if (min_x < a_group->srd_x)
> 				is_visible = GF_FALSE;
> 			else if (min_x > a_group->srd_x + a_group->srd_w)
> 				is_visible = GF_FALSE;
> 			else if (min_y < a_group->srd_y)
> 				is_visible = GF_FALSE;
> 			else if (min_y > a_group->srd_y + a_group->srd_h)
> 				is_visible = GF_FALSE;
> 		} else {
> 
> 			//single rectangle case
> 			if (min_x<max_x) {
> 				if (a_group->srd_x+a_group->srd_w <min_x) is_visible = GF_FALSE;
> 				else if (a_group->srd_x>max_x) is_visible = GF_FALSE;
> 			} else {
> 				if ( (a_group->srd_x>max_x) && (a_group->srd_x+a_group->srd_w<min_x)) is_visible = GF_FALSE;
> 			}
> 
> 			if (a_group->srd_y>max_y) is_visible = GF_FALSE;
> 			else if (a_group->srd_y+a_group->srd_h < min_y) is_visible = GF_FALSE;
> 
> 		}
> 		a_group->quality_degradation_hint = is_visible ? 0 : 100;
> 		
> 		GF_LOG(GF_LOG_DEBUG, GF_LOG_DASH, ("[DASH] Group SRD %d,%d,%d,%d is %s\n", a_group->srd_x, a_group->srd_w, a_group->srd_y, a_group->srd_h, is_visible ? "visible" : "hidden"));
>                 **if(check_v == a_group->quality_degradation_hint) continue;**
>                 gf_dash_set_tiles_quality(dash,a_group->srd_desc);
> 	}
> ```

Hi @eric3120925,thanks for sharing.

But I found that the time of image quality switching is longer than the dash time I set when I turned the FoV. 
For example, the dash time I set is 1s but when I turned the FoV, the image quality will change in 2s. Have you ever been in this situation？How can I make the time of image quality changing equal to the time I need？

I will be grateful for any help.

**Comment by a23232390** [comment]
How to set the FOV size

**Comment by jeanlf** [comment]
@a23232390, FOV is currently a single ray cast and has no size. It results in at most one tile being selected for high quality. You can always adjust the tile selection logic to include surrounding tiles in a custom DASH algo if needed.

I just updated the wiki [guide](https://github.com/gpac/gpac/wiki/HEVC-Tile-based-adaptation-guide) with points discussed here. Closing this, feel free to re-open or propose further clarifications.

**Comment by alstj908** [comment]
Hi how do I connect the c language code with gpac? I'm so desperate Thank you.
