### ISSUE TITLE
MP42TS : PTS Start time value

### ISSUE THREAD

**Issue by sanju-c** [gpac/gpac#1498]
I have this requirement where the PTS has to start at 4958860037 for the transport stream, but the -pcr-offset option for the MP42TS command seem to be taking maximum offset of 2147483647. If not with  -pcr-offset, is there any way with which I can have PTS starting at 4958860037  ?

**Comment by sanju-c** [comment]
Thanks for looking into it.
Requirement is to have PTS of both video and audio to start at 4958860037.
 
I also have similar requirement where I need a TS with 32 bit TEMI timeline starting at particular tick value and a TS with 64 bit TEMI timeline starting at particular tick value. Could you please tell if this can also be added where I can specify which timeline I want(32/64 bit) and also the starting tick value?
Note : My investigation is that the tool currently takes max temi offset of 27487791193 ticks and takes 32/64 bit media_timestamp based on the temi offset given

**Comment by jeanlf** [comment]
What if the PTS of first audio and video packets are different ? I think it would be wiser to remap the smallest PTS to the desired init value.

For TEMI, we will need to patch this in 0.9.0

**Comment by sanju-c** [comment]
The PTS of first audio and video packets should be same. Is it something not possible/difficult to map both the PTS to be of same value?

**Comment by jeanlf** [comment]
This is now supported through the `first_pts` option of the muxer.

**Comment by sanju-c** [comment]
looks like file size increases to large extent when I use this option

**Comment by sanju-c** [comment]
Also, can we make temi stream take 32 bit timeline alone and let it wrap after it reaches maximum rather than using 64 bit

**Comment by jeanlf** [comment]
indeed we were inserting PAT/PMT way too much, now fixed.
I also added the possibility to use only 32bit timecodes for TEMI.
Can you check if that's now OK?

**Comment by sanju-c** [comment]
Thank you, I will check it and also I get this 'PTS_Arrival_Error    PTS_PCR problem (PTS is -0.25ms in the past!!)' error for some of the video/audio packets on logs when I loaded the transport stream on dvb analyzer? If you could explain what could be the reason for it, could it be ignored since its in 0.25 ms?

**Comment by jeanlf** [comment]
I think this error was fixed in that commit, please re-check

**Comment by sanju-c** [comment]
I still get those error logs on dvb analyzer, mostly on the audio PID

**Comment by jeanlf** [comment]
hmm could you upload your input files ?
