### ISSUE TITLE
build fails due to  '/Users/lefeuvre' dependencies,...

### ISSUE THREAD

**Issue by Selur** [gpac/gpac#1509]
tons of references to '/Users/lefeuvre'
in
https://github.com/gpac/gpac/blob/master/src/modules/dektec_out/dektec_video_decl.dep
make build fail
with:
commit 9cc751217bd951cdfa5b32ea2d54e9fd370a3b5f (HEAD, tag: v1.0.1)

my build script looks like this
```
### MP4Box
if echo "$args" | grep -q -i -w -E 'all|mp4box'
then
  git clone https://github.com/gpac/gpac build
  cd build
  git checkout $(git tag --list | sort -V | tail -1)
  ./configure --static-mp4box \
    --disable-wx \
    --disable-alsa \
    --disable-jack \
    --disable-pulseaudio \
    --disable-x11 \
    --disable-ssl \
    --use-js=no \
    --use-faad=no \
    --use-mad=no \
    --use-xvid=no \
    --use-ffmpeg=no \
    --use-ogg=no \
    --use-vorbis=no \
    --use-theora=no \
    --use-openjpeg=no \
    --use-a52=no
  make $MAKEFLAGS || true
  strip bin/gcc/MP4Box
  cp -f bin/gcc/MP4Box ..
  cd ..
  rm -rf build
fi
```
and it fails with:
```
+ grep -q -i -w -E 'all|mp4box'
+ git clone https://github.com/gpac/gpac build
Cloning into 'build'...
remote: Enumerating objects: 173, done.
remote: Counting objects: 100% (173/173), done.
remote: Compressing objects: 100% (150/150), done.
remote: Total 139583 (delta 52), reused 70 (delta 17), pack-reused 139410
Receiving objects: 100% (139583/139583), 111.55 MiB | 11.41 MiB/s, done.
Resolving deltas: 100% (113463/113463), done.
+ cd build
++ git tag --list
++ sort -V
++ tail -1
+ git checkout v1.0.1
Note: checking out 'v1.0.1'.

You are in 'detached HEAD' state. You can look around, make experimental
changes and commit them, and you can discard any commits you make in this
state without impacting any branches by performing another checkout.

If you want to create a new branch to retain commits you create, you may
do so (now or later) by using -b with the checkout command again. Example:

  git checkout -b <new-branch-name>

HEAD is now at 9cc751217 fixed changelog for 1.0
+ ./configure --static-mp4box --disable-wx --disable-alsa --disable-jack --disable-pulseaudio --disable-x11 --disable-ssl --use-js=no --use-faad=no --use-mad=no --use-xvid=no --use-ffmpeg=no --use-ogg=no --use-vorbis=no --use-theora=no --use-openjpeg=no --use-a52=no
diff: ./include/gpac/revision.h: No such file or directory
revision has changed
rm: cannot remove './include/gpac/revision.h': No such file or directory

** System Configuration
Install prefix: /usr/local
Source path: /home/selur/workspace/HybridTools/tools/build
C   compiler: gcc
C++ compiler: g++
make: make
CPU: x86_64
Big Endian: no

** GPAC 1.0.0 rev Core Configuration **
debug version: no
GProf enabled: no
Static build enabled: yes
Memory tracking enabled: no
Sanitizer enabled: no
Fixed-Point Version: no
IPV6 Support: yes
Static Modules: no
QuickJS Support: yes

** Detected libraries **
zlib: system
OSS Audio: yes
ALSA Audio: no
Jack Audio: no
PulseAudio Audio: no
DirectFB support: no
SDL Support: no
OpenGL support: no
TinyGL support: no
OpenSSL support: no
DVB Support: yes

** Extra Libraries used **
FreeType: no
JPEG: no
OpenJPEG: no
PNG: no
MAD: no
FAAD: no
XVID: no
FFMPEG: no
LZMA: yes
Xiph OGG: no
Platinum UPnP: no
AVCap: no
A52 (AC3): no
OpenSVCDecoder: no
OpenHEVCDecoder: no
Freenect: no

Creating config.mak
Check config.log for detection failures
Done - type 'make help' for make info, 'make' to build
+ make -j4
make -C src all
make[1]: Entering directory '/home/selur/workspace/HybridTools/tools/build/src'
cat .deps/utils/os_divers.dep .deps/utils/os_file.dep .deps/utils/list.dep .deps/utils/bitstream.dep .deps/utils/constants.dep .deps/utils/error.dep .deps/utils/alloc.dep .deps/utils/url.dep .deps/utils/configfile.dep .deps/utils/gltools.dep .deps/utils/gzio.dep .deps/utils/sha1.dep .deps/utils/base_encoding.dep .deps/utils/math.dep .deps/utils/os_net.dep .deps/utils/os_thread.dep .deps/utils/os_config_init.dep .deps/utils/cache.dep .deps/utils/downloader.dep .deps/utils/xml_parser.dep .deps/utils/utf.dep .deps/utils/token.dep .deps/utils/color.dep .deps/utils/Remotery.dep .deps/utils/os_module.dep .deps/utils/path2d.dep .deps/utils/path2d_stroker.dep .deps/utils/module.dep .deps/utils/uni_bidi.dep .deps/utils/unicode.dep .deps/crypto/g_crypt.dep .deps/crypto/g_crypt_openssl.dep .deps/crypto/g_crypt_tinyaes.dep .deps/crypto/tiny_aes.dep .deps/scenegraph/base_scenegraph.dep .deps/scenegraph/mpeg4_animators.dep .deps/scenegraph/commands.dep .deps/scenegraph/mpeg4_nodes.dep .deps/scenegraph/mpeg4_valuator.dep .deps/scenegraph/vrml_interpolators.dep .deps/scenegraph/vrml_proto.dep .deps/scenegraph/vrml_route.dep .deps/scenegraph/vrml_script.dep .deps/scenegraph/vrml_js.dep .deps/scenegraph/vrml_tools.dep .deps/scenegraph/x3d_nodes.dep .deps/scenegraph/svg_attributes.dep .deps/scenegraph/svg_types.dep .deps/scenegraph/svg_js.dep .deps/scenegraph/smil_anim.dep .deps/scenegraph/smil_timing.dep .deps/scenegraph/svg_properties.dep .deps/scenegraph/dom_events.dep .deps/scenegraph/dom_js.dep .deps/scenegraph/xml_ns.dep .deps/ietf/rtcp.dep .deps/ietf/rtp.dep .deps/ietf/rtp_packetizer.dep .deps/ietf/rtp_pck_3gpp.dep .deps/ietf/rtp_pck_mpeg12.dep .deps/ietf/rtp_pck_mpeg4.dep .deps/ietf/rtsp_command.dep .deps/ietf/rtsp_common.dep .deps/ietf/rtsp_response.dep .deps/ietf/rtsp_session.dep .deps/ietf/sdp.dep .deps/ietf/rtp_depacketizer.dep .deps/ietf/rtp_streamer.dep .deps/bifs/arith_decoder.dep .deps/bifs/bifs_codec.dep .deps/bifs/bifs_node_tables.dep .deps/bifs/com_dec.dep .deps/bifs/com_enc.dep .deps/bifs/conditional.dep .deps/bifs/field_decode.dep .deps/bifs/field_encode.dep .deps/bifs/memory_decoder.dep .deps/bifs/predictive_mffield.dep .deps/bifs/quantize.dep .deps/bifs/script_dec.dep .deps/bifs/script_enc.dep .deps/bifs/unquantize.dep .deps/isomedia/avc_ext.dep .deps/isomedia/box_code_3gpp.dep .deps/isomedia/box_code_apple.dep .deps/isomedia/box_code_base.dep .deps/isomedia/box_code_drm.dep .deps/isomedia/box_code_meta.dep .deps/isomedia/box_dump.dep .deps/isomedia/box_funcs.dep .deps/isomedia/data_map.dep .deps/isomedia/drm_sample.dep .deps/isomedia/isom_intern.dep .deps/isomedia/isom_read.dep .deps/isomedia/isom_store.dep .deps/isomedia/isom_write.dep .deps/isomedia/media.dep .deps/isomedia/media_odf.dep .deps/isomedia/meta.dep .deps/isomedia/movie_fragments.dep .deps/isomedia/sample_descs.dep .deps/isomedia/stbl_read.dep .deps/isomedia/stbl_write.dep .deps/isomedia/track.dep .deps/isomedia/tx3g.dep .deps/isomedia/iff.dep .deps/isomedia/hint_track.dep .deps/isomedia/hinting.dep .deps/isomedia/box_code_adobe.dep .deps/odf/desc_private.dep .deps/odf/descriptors.dep .deps/odf/odf_code.dep .deps/odf/odf_codec.dep .deps/odf/odf_command.dep .deps/odf/qos.dep .deps/odf/slc.dep .deps/odf/ipmpx_code.dep .deps/odf/oci_codec.dep .deps/odf/ipmpx_dump.dep .deps/odf/ipmpx_parse.dep .deps/odf/odf_dump.dep .deps/odf/odf_parse.dep .deps/media_tools/isom_tools.dep .deps/media_tools/dash_segmenter.dep .deps/media_tools/av_parsers.dep .deps/media_tools/atsc_dmx.dep .deps/media_tools/img.dep .deps/media_tools/media_import.dep .deps/media_tools/mpegts.dep .deps/media_tools/m3u8.dep .deps/media_tools/mpd.dep .deps/media_tools/dash_client.dep .deps/media_tools/media_export.dep .deps/media_tools/m2ts_mux.dep .deps/media_tools/avilib.dep .deps/media_tools/mpeg2_ps.dep .deps/media_tools/gpac_ogg.dep .deps/media_tools/crypt_tools.dep .deps/media_tools/isom_hinter.dep .deps/media_tools/saf.dep .deps/media_tools/vobsub.dep .deps/media_tools/webvtt.dep .deps/scene_manager/scene_manager.dep .deps/scene_manager/text_to_bifs.dep .deps/scene_manager/loader_bt.dep .deps/scene_manager/loader_xmt.dep .deps/scene_manager/loader_isom.dep .deps/scene_manager/loader_qt.dep .deps/scene_manager/loader_svg.dep .deps/scene_manager/swf_parse.dep .deps/scene_manager/swf_bifs.dep .deps/scene_manager/swf_svg.dep .deps/scene_manager/scene_dump.dep .deps/scene_manager/scene_stats.dep .deps/scene_manager/scene_engine.dep .deps/scene_manager/encode_isom.dep .deps/terminal/terminal.dep .deps/compositor/audio_input.dep .deps/compositor/audio_mixer.dep .deps/compositor/audio_render.dep .deps/compositor/bindable.dep .deps/compositor/camera.dep .deps/compositor/compositor.dep .deps/compositor/compositor_2d.dep .deps/compositor/compositor_3d.dep .deps/compositor/compositor_node_init.dep .deps/compositor/drawable.dep .deps/compositor/events.dep .deps/compositor/font_engine.dep .deps/compositor/hc_flash_shape.dep .deps/compositor/hardcoded_protos.dep .deps/compositor/mesh.dep .deps/compositor/mesh_collide.dep .deps/compositor/mesh_tesselate.dep .deps/compositor/mpeg4_animstream.dep .deps/compositor/mpeg4_audio.dep .deps/compositor/mpeg4_background.dep .deps/compositor/mpeg4_background2d.dep .deps/compositor/mpeg4_bitmap.dep .deps/compositor/mpeg4_composite.dep .deps/compositor/mpeg4_form.dep .deps/compositor/mpeg4_geometry_2d.dep .deps/compositor/mpeg4_geometry_3d.dep .deps/compositor/mpeg4_geometry_ifs2d.dep .deps/compositor/mpeg4_geometry_ils2d.dep .deps/compositor/mpeg4_gradients.dep .deps/compositor/mpeg4_grouping.dep .deps/compositor/mpeg4_grouping_2d.dep .deps/compositor/mpeg4_grouping_3d.dep .deps/compositor/mpeg4_layer_2d.dep .deps/compositor/mpeg4_layer_3d.dep .deps/compositor/mpeg4_layout.dep .deps/compositor/mpeg4_lighting.dep .deps/compositor/mpeg4_path_layout.dep .deps/compositor/mpeg4_sensors.dep .deps/compositor/mpeg4_sound.dep .deps/compositor/mpeg4_text.dep .deps/compositor/mpeg4_textures.dep .deps/compositor/mpeg4_timesensor.dep .deps/compositor/mpeg4_viewport.dep .deps/compositor/navigate.dep .deps/compositor/offscreen_cache.dep .deps/compositor/svg_base.dep .deps/compositor/svg_filters.dep .deps/compositor/svg_font.dep .deps/compositor/svg_geometry.dep .deps/compositor/svg_grouping.dep .deps/compositor/svg_media.dep .deps/compositor/svg_paint_servers.dep .deps/compositor/svg_text.dep .deps/compositor/texturing.dep .deps/compositor/texturing_gl.dep .deps/compositor/visual_manager.dep .deps/compositor/visual_manager_2d.dep .deps/compositor/visual_manager_2d_draw.dep .deps/compositor/visual_manager_3d.dep .deps/compositor/visual_manager_3d_gl.dep .deps/compositor/x3d_geometry.dep .deps/compositor/clock.dep .deps/compositor/mpeg4_inputsensor.dep .deps/compositor/mpeg4_mediacontrol.dep .deps/compositor/media_object.dep .deps/compositor/mpeg4_mediasensor.dep .deps/compositor/mpeg4_inline.dep .deps/compositor/scene_ns.dep .deps/compositor/object_manager.dep .deps/compositor/scene.dep .deps/compositor/svg_external.dep .deps/compositor/scene_node_init.dep .deps/laser/lsr_enc.dep .deps/laser/lsr_dec.dep .deps/laser/lsr_tables.dep .deps/evg/ftgrays.dep .deps/evg/raster3d.dep .deps/evg/raster_565.dep .deps/evg/raster_argb.dep .deps/evg/raster_rgb.dep .deps/evg/raster_yuv.dep .deps/evg/stencil.dep .deps/evg/surface.dep .deps/filter_core/filter_pck.dep .deps/filter_core/filter_pid.dep .deps/filter_core/filter_props.dep .deps/filter_core/filter_queue.dep .deps/filter_core/filter_session.dep .deps/filter_core/filter_register.dep .deps/filter_core/filter.dep .deps/filters/bsrw.dep .deps/filters/compose.dep .deps/filters/dasher.dep .deps/filters/dec_ac52.dep .deps/filters/dec_bifs.dep .deps/filters/dec_faad.dep .deps/filters/dec_img.dep .deps/filters/dec_j2k.dep .deps/filters/dec_laser.dep .deps/filters/dec_mad.dep .deps/filters/dec_mediacodec.dep .deps/filters/dec_nvdec.dep .deps/filters/dec_nvdec_sdk.dep .deps/filters/dec_odf.dep .deps/filters/dec_theora.dep .deps/filters/dec_ttml.dep .deps/filters/dec_ttxt.dep .deps/filters/dec_vorbis.dep .deps/filters/dec_vtb.dep .deps/filters/dec_webvtt.dep .deps/filters/dec_xvid.dep .deps/filters/decrypt_cenc_isma.dep .deps/filters/dmx_avi.dep .deps/filters/dmx_dash.dep .deps/filters/dmx_gsf.dep .deps/filters/dmx_m2ts.dep .deps/filters/dmx_mpegps.dep .deps/filters/dmx_nhml.dep .deps/filters/dmx_nhnt.dep .deps/filters/dmx_ogg.dep .deps/filters/dmx_saf.dep .deps/filters/dmx_vobsub.dep .deps/filters/enc_jpg.dep .deps/filters/enc_png.dep .deps/filters/encrypt_cenc_isma.dep .deps/filters/ff_common.dep .deps/filters/ff_avf.dep .deps/filters/ff_dec.dep .deps/filters/ff_dmx.dep .deps/filters/ff_enc.dep .deps/filters/ff_rescale.dep .deps/filters/ff_mx.dep .deps/filters/filelist.dep .deps/filters/hevcmerge.dep .deps/filters/hevcsplit.dep .deps/filters/in_atsc.dep .deps/filters/in_dvb4linux.dep .deps/filters/in_file.dep .deps/filters/in_http.dep .deps/filters/in_pipe.dep .deps/filters/in_rtp.dep .deps/filters/in_rtp_rtsp.dep .deps/filters/in_rtp_sdp.dep .deps/filters/in_rtp_signaling.dep .deps/filters/in_rtp_stream.dep .deps/filters/in_sock.dep .deps/filters/inspect.dep .deps/filters/isoffin_load.dep .deps/filters/isoffin_read.dep .deps/filters/isoffin_read_ch.dep .deps/filters/jsfilter.dep .deps/filters/load_bt_xmt.dep .deps/filters/load_svg.dep .deps/filters/load_text.dep .deps/filters/mux_avi.dep .deps/filters/mux_gsf.dep .deps/filters/mux_isom.dep .deps/filters/mux_ts.dep .deps/filters/out_audio.dep .deps/filters/out_file.dep .deps/filters/out_http.dep .deps/filters/out_pipe.dep .deps/filters/out_rtp.dep .deps/filters/out_rtsp.dep .deps/filters/out_sock.dep .deps/filters/out_video.dep .deps/filters/reframer.dep .deps/filters/reframe_ac3.dep .deps/filters/reframe_adts.dep .deps/filters/reframe_latm.dep .deps/filters/reframe_amr.dep .deps/filters/reframe_av1.dep .deps/filters/reframe_flac.dep .deps/filters/reframe_h263.dep .deps/filters/reframe_img.dep .deps/filters/reframe_mp3.dep .deps/filters/reframe_mpgvid.dep .deps/filters/reframe_nalu.dep .deps/filters/reframe_prores.dep .deps/filters/reframe_qcp.dep .deps/filters/reframe_rawvid.dep .deps/filters/reframe_rawpcm.dep .deps/filters/resample_audio.dep .deps/filters/tileagg.dep .deps/filters/tssplit.dep .deps/filters/unit_test_filter.dep .deps/filters/rewind.dep .deps/filters/rewrite_adts.dep .deps/filters/rewrite_mp4v.dep .deps/filters/rewrite_nalu.dep .deps/filters/rewrite_obu.dep .deps/filters/vflip.dep .deps/filters/vcrop.dep .deps/filters/write_generic.dep .deps/filters/write_nhml.dep .deps/filters/write_nhnt.dep .deps/filters/write_qcp.dep .deps/filters/write_vtt.dep .deps/../modules/dektec_out/dektec_video_decl.dep .deps/filters/dec_opensvc.dep .deps/quickjs/cutils.dep .deps/quickjs/libbf.dep .deps/quickjs/libregexp.dep .deps/quickjs/libunicode.dep .deps/quickjs/quickjs.dep .deps/jsmods/evg.dep .deps/jsmods/scene_js.dep .deps/jsmods/storage.dep .deps/jsmods/webgl.dep .deps/jsmods/xhr.dep > ".depend"
  CC utils/os_file.c
  CC utils/os_divers.c
  CC utils/list.c
  CC utils/bitstream.c
  CC utils/constants.c
  CC utils/error.c
  CC utils/alloc.c
  CC utils/url.c
  CC utils/configfile.c
  CC utils/gltools.c
  CC utils/gzio.c
  CC utils/sha1.c
  CC utils/base_encoding.c
  CC utils/math.c
  CC utils/os_net.c
  CC utils/os_thread.c
  CC utils/os_config_init.c
  CC utils/cache.c
  CC utils/downloader.c
  CC utils/xml_parser.c
  CC utils/utf.c
  CC utils/token.c
  CC utils/color.c
  CC utils/Remotery.c
  CC utils/os_module.c
  CC utils/path2d.c
  CC utils/path2d_stroker.c
  CC utils/module.c
  CC utils/uni_bidi.c
  CC utils/unicode.c
  CC ietf/rtcp.c
  CC ietf/rtp.c
  CC ietf/rtp_packetizer.c
  CC ietf/rtp_pck_3gpp.c
  CC ietf/rtp_pck_mpeg12.c
  CC ietf/rtp_pck_mpeg4.c
  CC ietf/rtsp_command.c
  CC ietf/rtsp_common.c
  CC ietf/rtsp_response.c
  CC ietf/rtsp_session.c
  CC ietf/sdp.c
  CC ietf/rtp_depacketizer.c
  CC ietf/rtp_streamer.c
  CC bifs/arith_decoder.c
  CC bifs/bifs_codec.c
  CC bifs/bifs_node_tables.c
  CC bifs/com_dec.c
  CC bifs/com_enc.c
  CC bifs/conditional.c
  CC bifs/field_decode.c
  CC bifs/field_encode.c
  CC bifs/memory_decoder.c
  CC bifs/predictive_mffield.c
  CC bifs/quantize.c
  CC bifs/script_dec.c
  CC bifs/script_enc.c
  CC bifs/unquantize.c
  CC odf/desc_private.c
  CC odf/descriptors.c
  CC odf/odf_code.c
  CC odf/odf_codec.c
  CC odf/odf_command.c
  CC odf/qos.c
  CC odf/slc.c
  CC odf/ipmpx_code.c
  CC odf/oci_codec.c
  CC odf/ipmpx_dump.c
  CC odf/ipmpx_parse.c
  CC odf/odf_dump.c
  CC odf/odf_parse.c
  CC laser/lsr_enc.c
  CC laser/lsr_dec.c
  CC laser/lsr_tables.c
  CC isomedia/avc_ext.c
  CC isomedia/box_code_3gpp.c
  CC isomedia/box_code_apple.c
  CC isomedia/box_code_base.c
  CC isomedia/box_code_drm.c
  CC isomedia/box_code_meta.c
  CC isomedia/box_dump.c
  CC isomedia/box_funcs.c
  CC isomedia/data_map.c
  CC isomedia/drm_sample.c
  CC isomedia/isom_intern.c
  CC isomedia/isom_read.c
  CC isomedia/isom_store.c
  CC isomedia/isom_write.c
  CC isomedia/media.c
  CC isomedia/media_odf.c
  CC isomedia/meta.c
  CC isomedia/movie_fragments.c
  CC isomedia/sample_descs.c
  CC isomedia/stbl_read.c
  CC isomedia/stbl_write.c
  CC isomedia/track.c
  CC isomedia/tx3g.c
  CC isomedia/iff.c
  CC isomedia/hint_track.c
  CC isomedia/hinting.c
  CC isomedia/box_code_adobe.c
  CC scene_manager/scene_manager.c
  CC scene_manager/text_to_bifs.c
  CC scene_manager/loader_bt.c
  CC scene_manager/loader_xmt.c
  CC scene_manager/loader_isom.c
  CC scene_manager/loader_qt.c
  CC scene_manager/loader_svg.c
  CC scene_manager/swf_parse.c
  CC scene_manager/swf_bifs.c
  CC scene_manager/swf_svg.c
  CC scene_manager/scene_dump.c
  CC scene_manager/scene_stats.c
  CC scene_manager/scene_engine.c
  CC scene_manager/encode_isom.c
  CC terminal/terminal.c
  CC compositor/audio_input.c
  CC compositor/audio_mixer.c
  CC compositor/audio_render.c
  CC compositor/bindable.c
  CC compositor/camera.c
  CC compositor/compositor.c
  CC compositor/compositor_2d.c
  CC compositor/compositor_3d.c
  CC compositor/compositor_node_init.c
  CC compositor/drawable.c
  CC compositor/events.c
  CC compositor/font_engine.c
  CC compositor/hc_flash_shape.c
  CC compositor/hardcoded_protos.c
  CC compositor/mesh.c
  CC compositor/mesh_collide.c
  CC compositor/mesh_tesselate.c
  CC compositor/mpeg4_animstream.c
  CC compositor/mpeg4_audio.c
  CC compositor/mpeg4_background.c
  CC compositor/mpeg4_background2d.c
  CC compositor/mpeg4_bitmap.c
  CC compositor/mpeg4_composite.c
  CC compositor/mpeg4_form.c
  CC compositor/mpeg4_geometry_2d.c
  CC compositor/mpeg4_geometry_3d.c
  CC compositor/mpeg4_geometry_ifs2d.c
  CC compositor/mpeg4_geometry_ils2d.c
  CC compositor/mpeg4_gradients.c
  CC compositor/mpeg4_grouping.c
  CC compositor/mpeg4_grouping_2d.c
  CC compositor/mpeg4_grouping_3d.c
  CC compositor/mpeg4_layer_2d.c
  CC compositor/mpeg4_layer_3d.c
  CC compositor/mpeg4_layout.c
  CC compositor/mpeg4_lighting.c
  CC compositor/mpeg4_path_layout.c
  CC compositor/mpeg4_sensors.c
  CC compositor/mpeg4_sound.c
  CC compositor/mpeg4_text.c
  CC compositor/mpeg4_textures.c
  CC compositor/mpeg4_timesensor.c
  CC compositor/mpeg4_viewport.c
  CC compositor/navigate.c
  CC compositor/offscreen_cache.c
  CC compositor/svg_base.c
  CC compositor/svg_filters.c
  CC compositor/svg_font.c
  CC compositor/svg_geometry.c
  CC compositor/svg_grouping.c
  CC compositor/svg_media.c
  CC compositor/svg_paint_servers.c
  CC compositor/svg_text.c
  CC compositor/texturing.c
  CC compositor/texturing_gl.c
  CC compositor/visual_manager.c
  CC compositor/visual_manager_2d.c
  CC compositor/visual_manager_2d_draw.c
  CC compositor/visual_manager_3d.c
  CC compositor/visual_manager_3d_gl.c
  CC compositor/x3d_geometry.c
  CC compositor/clock.c
  CC compositor/mpeg4_inputsensor.c
  CC compositor/mpeg4_mediacontrol.c
  CC compositor/media_object.c
  CC compositor/mpeg4_mediasensor.c
  CC compositor/mpeg4_inline.c
  CC compositor/scene_ns.c
  CC compositor/object_manager.c
  CC compositor/scene.c
  CC compositor/svg_external.c
  CC compositor/scene_node_init.c
  CC scenegraph/base_scenegraph.c
  CC scenegraph/mpeg4_animators.c
  CC scenegraph/commands.c
  CC scenegraph/mpeg4_nodes.c
  CC scenegraph/mpeg4_valuator.c
  CC scenegraph/vrml_interpolators.c
  CC scenegraph/vrml_proto.c
  CC scenegraph/vrml_route.c
  CC scenegraph/vrml_script.c
  CC scenegraph/vrml_js.c
  CC scenegraph/vrml_tools.c
  CC scenegraph/x3d_nodes.c
  CC scenegraph/svg_attributes.c
  CC scenegraph/svg_types.c
  CC scenegraph/svg_js.c
  CC scenegraph/smil_anim.c
  CC scenegraph/smil_timing.c
  CC scenegraph/svg_properties.c
  CC scenegraph/dom_events.c
  CC scenegraph/dom_js.c
  CC scenegraph/xml_ns.c
  CC media_tools/isom_tools.c
  CC media_tools/dash_segmenter.c
  CC media_tools/av_parsers.c
  CC media_tools/atsc_dmx.c
  CC media_tools/img.c
  CC media_tools/media_import.c
  CC media_tools/mpegts.c
  CC media_tools/m3u8.c
  CC media_tools/mpd.c
  CC media_tools/dash_client.c
  CC media_tools/media_export.c
  CC media_tools/m2ts_mux.c
  CC media_tools/avilib.c
  CC media_tools/mpeg2_ps.c
  CC media_tools/gpac_ogg.c
  CC media_tools/crypt_tools.c
  CC media_tools/isom_hinter.c
  CC media_tools/saf.c
  CC media_tools/vobsub.c
  CC media_tools/webvtt.c
  CC crypto/g_crypt.c
  CC crypto/g_crypt_openssl.c
  CC crypto/g_crypt_tinyaes.c
  CC crypto/tiny_aes.c
  CC filter_core/filter_pck.c
  CC filter_core/filter_pid.c
  CC filter_core/filter_props.c
  CC filter_core/filter_queue.c
  CC filter_core/filter_session.c
  CC filter_core/filter_register.c
  CC filter_core/filter.c
  CC filters/bsrw.c
  CC filters/compose.c
  CC filters/dasher.c
  CC filters/dec_ac52.c
  CC filters/dec_bifs.c
  CC filters/dec_faad.c
  CC filters/dec_img.c
  CC filters/dec_j2k.c
  CC filters/dec_mad.c
  CC filters/dec_laser.c
  CC filters/dec_mediacodec.c
  CC filters/dec_nvdec.c
  CC filters/dec_nvdec_sdk.c
  CC filters/dec_odf.c
  CC filters/dec_theora.c
  CC filters/dec_ttml.c
  CC filters/dec_ttxt.c
  CC filters/dec_vorbis.c
  CC filters/dec_vtb.c
  CC filters/dec_webvtt.c
  CC filters/dec_xvid.c
  CC filters/decrypt_cenc_isma.c
  CC filters/dmx_avi.c
  CC filters/dmx_dash.c
  CC filters/dmx_gsf.c
  CC filters/dmx_m2ts.c
  CC filters/dmx_mpegps.c
  CC filters/dmx_nhml.c
  CC filters/dmx_nhnt.c
  CC filters/dmx_ogg.c
  CC filters/dmx_saf.c
  CC filters/dmx_vobsub.c
  CC filters/enc_jpg.c
  CC filters/enc_png.c
  CC filters/encrypt_cenc_isma.c
  CC filters/ff_common.c
  CC filters/ff_avf.c
  CC filters/ff_dec.c
  CC filters/ff_dmx.c
  CC filters/ff_enc.c
  CC filters/ff_rescale.c
  CC filters/ff_mx.c
  CC filters/filelist.c
  CC filters/hevcmerge.c
  CC filters/hevcsplit.c
  CC filters/in_atsc.c
  CC filters/in_dvb4linux.c
  CC filters/in_file.c
  CC filters/in_http.c
  CC filters/in_pipe.c
  CC filters/in_rtp.c
  CC filters/in_rtp_rtsp.c
  CC filters/in_rtp_sdp.c
  CC filters/in_rtp_signaling.c
  CC filters/in_rtp_stream.c
  CC filters/in_sock.c
  CC filters/inspect.c
  CC filters/isoffin_load.c
  CC filters/isoffin_read.c
  CC filters/isoffin_read_ch.c
  CC filters/jsfilter.c
  CC filters/load_bt_xmt.c
  CC filters/load_svg.c
  CC filters/load_text.c
  CC filters/mux_avi.c
  CC filters/mux_gsf.c
  CC filters/mux_isom.c
  CC filters/mux_ts.c
  CC filters/out_audio.c
  CC filters/out_file.c
  CC filters/out_http.c
  CC filters/out_pipe.c
  CC filters/out_rtp.c
  CC filters/out_rtsp.c
  CC filters/out_sock.c
  CC filters/out_video.c
  CC filters/reframer.c
  CC filters/reframe_ac3.c
  CC filters/reframe_adts.c
  CC filters/reframe_latm.c
  CC filters/reframe_amr.c
  CC filters/reframe_av1.c
  CC filters/reframe_flac.c
  CC filters/reframe_h263.c
  CC filters/reframe_img.c
  CC filters/reframe_mp3.c
  CC filters/reframe_mpgvid.c
  CC filters/reframe_nalu.c
  CC filters/reframe_prores.c
  CC filters/reframe_qcp.c
  CC filters/reframe_rawvid.c
  CC filters/reframe_rawpcm.c
  CC filters/resample_audio.c
  CC filters/tileagg.c
  CC filters/tssplit.c
  CC filters/unit_test_filter.c
  CC filters/rewind.c
  CC filters/rewrite_adts.c
  CC filters/rewrite_mp4v.c
  CC filters/rewrite_nalu.c
  CC filters/rewrite_obu.c
  CC filters/vflip.c
  CC filters/vcrop.c
  CC filters/write_generic.c
  CC filters/write_nhml.c
  CC filters/write_nhnt.c
  CC filters/write_qcp.c
make[1]: *** No rule to make target '/Users/lefeuvre/code/gpac/include/gpac/filters.h', needed by '../modules/dektec_out/dektec_video_decl.o'.  Stop.
make[1]: *** Waiting for unfinished jobs....
  CC filters/write_vtt.c
make[1]: Leaving directory '/home/selur/workspace/HybridTools/tools/build/src'
Makefile:13: recipe for target 'all' failed
make: *** [all] Error 2
```

**Comment by jeanlf** [comment]
no clue how this ended up here ! Should now be fixed, can you check ?

**Comment by Selur** [comment]
Nope, still fails with:
```
...
  CC filters/write_nhnt.c
  CC filters/write_qcp.c
make[1]: *** No rule to make target '/Users/lefeuvre/code/gpac/include/gpac/filters.h', needed by '../modules/dektec_out/dektec_video_decl.o'.  Stop.
make[1]: *** Waiting for unfinished jobs....
  CC filters/write_vtt.c
make[1]: Leaving directory '/home/selur/workspace/HybridTools/tools/build/src'
Makefile:13: recipe for target 'all' failed
make: *** [all] Error 2
+ true
+ strip bin/gcc/MP4Box
strip: 'bin/gcc/MP4Box': No such file
```
(I deleted the old build folder to be sure)

**Comment by Selur** [comment]
doh will try again,.. forgot about the '$(git tag --list | sort -V | tail -1)'

**Comment by Selur** [comment]
-> works fine now :)

**Comment by jeanlf** [comment]
OK we will retag 1.0 to include both #1508 and #1509 - many thanks for the report
