### ISSUE TITLE
android load libs fail

### ISSUE THREAD

**Issue by SivanLiu** [gpac/gpac#1529]
Thanks for reporting your issue. Please make sure these boxes are checked before submitting your issue - thank you!

- [x] I looked for a similar issue and couldn't find any.
- [x] I tried with the latest version of GPAC. Installers available at http://gpac.io/downloads/gpac-nightly-builds/
- [x] I give enough information for contributors to reproduce my issue (meaningful title, github labels, platform and compiler, command-line ...). I can share files anonymously with this dropbox: https://www.mediafire.com/filedrop/filedrop_hosted.php?drop=eec9e058a9486fe4e99c33021481d9e1826ca9dbc242a6cfaab0fe95da5e5d95

Detailed guidelines: http://gpac.io/2013/07/16/how-to-file-a-bug-properly/

I have tested 0.8.1 and 1.0 lastest apk on android 6 8 9 10，0.8.1 is normal，but 1.0 lastest can't load libs normally，the log is below:

$Revision$
Mon Jun 29 16:39:32 GMT+08:00 2020

*** Configuration

GpacAppDirectory=/data/data/com.gpac.Osmo4/
GpacModulesDirectory=/data/data/com.gpac.Osmo4/lib/
GpacFontDirectory=/system/fonts/
GpacCacheDirectory=/data/data/com.gpac.Osmo4/cache
GpacGuiDirectory=/data/data/com.gpac.Osmo4/share/gui/
GpacShaderDirectory=/data/data/com.gpac.Osmo4/share/shaders/

Loading library GLESv2...Loading library log...Loading library jpegdroid...Loading library javaenv...Loading library mad...Loading library editline...Loading library ft2...Loading library js_osmo...Loading library openjpeg...Loading library png...Loading library z...Loading library stlport_shared...Loading library stdc++...Loading library faad...Loading library gpac...Loading library gm_droid_mpegv...Loading library gm_mediacodec_dec...Failed to load gm_mediacodec_dec, error=dalvik.system.PathClassLoader[DexPathList[[zip file "/data/app/com.gpac.Osmo4-1/base.apk"],nativeLibraryDirectories=[/data/app/com.gpac.Osmo4-1/lib/arm, /vendor/lib, /system/lib]]] couldn't find "libgm_mediacodec_dec.so" :: UnsatisfiedLinkError
Loading library avutil...Loading library swscale...Loading library swresample...Loading library avcodec...Loading library avformat...Loading library avfilter...Loading library avdevice...Loading library gpacWrapper...*** Libs listing: /data/data/com.gpac.Osmo4/lib/
  libstlport_shared.so [399384 bytes]
  libavfilter.so [1504740 bytes]
  libopenjpeg.so [89296 bytes]
  libavdevice.so [51108 bytes]
  libjs_osmo.so [523656 bytes]
  libgm_droid_audio.so [17884 bytes]
  libfaad.so [221720 bytes]
  libeditline.so [30552 bytes]
  libgpac.so [4559404 bytes]
  libavcodec.so [12169464 bytes]
  libft2.so [345604 bytes]
  libmad.so [99844 bytes]
  libz.so [87632 bytes]
  libgm_droid_out.so [21980 bytes]
  libpng.so [120376 bytes]
  libgm_ft_font.so [22056 bytes]
  libavutil.so [255452 bytes]
  libjavaenv.so [13728 bytes]
  libgpacWrapper.so [100072 bytes]
  libswscale.so [320908 bytes]
  libswresample.so [75148 bytes]
  libjpegdroid.so [157188 bytes]
  libavformat.so [1666644 bytes]
  libgm_droid_mpegv.so [17884 bytes]
*** Modules listing: /data/data/com.gpac.Osmo4/lib/
  libstlport_shared.so [399384 bytes]
  libavfilter.so [1504740 bytes]
  libopenjpeg.so [89296 bytes]
  libavdevice.so [51108 bytes]
  libjs_osmo.so [523656 bytes]
  libgm_droid_audio.so [17884 bytes]
  libfaad.so [221720 bytes]
  libeditline.so [30552 bytes]
  libgpac.so [4559404 bytes]
  libavcodec.so [12169464 bytes]
  libft2.so [345604 bytes]
  libmad.so [99844 bytes]
  libz.so [87632 bytes]
  libgm_droid_out.so [21980 bytes]
  libpng.so [120376 bytes]
  libgm_ft_font.so [22056 bytes]
  libavutil.so [255452 bytes]
  libjavaenv.so [13728 bytes]
  libgpacWrapper.so [100072 bytes]
  libswscale.so [320908 bytes]
  libswresample.so [75148 bytes]
  libjpegdroid.so [157188 bytes]
  libavformat.so [1666644 bytes]
  libgm_droid_mpegv.so [17884 bytes]
*** Fonts listing: 
/system/fonts/
  AndroidClock.ttf [4540 bytes]
  AndroidClock_Highlight.ttf [4464 bytes]
  AndroidClock_Solid.ttf [4464 bytes]
  CarroisGothicSC-Regular.ttf [40308 bytes]
  Clockopia.ttf [6564 bytes]
  ComingSoon.ttf [59136 bytes]
  CutiveMono.ttf [69180 bytes]
  DancingScript-Bold.ttf [115568 bytes]
  DancingScript-Regular.ttf [116580 bytes]
  DroidSansMono.ttf [108128 bytes]
  Lohit-Odia.ttf [97872 bytes]
  MTLmr3m.ttf [2558716 bytes]
  NotoColorEmoji.ttf [2317800 bytes]
  NotoNaskh-Bold.ttf [114612 bytes]
  NotoNaskh-Regular.ttf [115540 bytes]
  NotoNaskhUI-Bold.ttf [114596 bytes]
  NotoNaskhUI-Regular.ttf [115700 bytes]
  NotoSansArmenian-Bold.ttf [14152 bytes]
  NotoSansArmenian-Regular.ttf [14324 bytes]
  NotoSansBalinese-Regular.ttf [31604 bytes]
  NotoSansBatak-Regular.ttf [12472 bytes]
  NotoSansBengali-Bold.ttf [98100 bytes]
  NotoSansBengali-Regular.ttf [101308 bytes]
  NotoSansBengaliUI-Bold.ttf [103532 bytes]
  NotoSansBengaliUI-Regular.ttf [106640 bytes]
  NotoSansBuginese-Regular.ttf [7028 bytes]
  NotoSansBuhid-Regular.ttf [4460 bytes]
  NotoSansCanadianAboriginal-Regular.ttf [47268 bytes]
  NotoSansCham-Bold.ttf [22056 bytes]
  NotoSansCham-Regular.ttf [22048 bytes]
  NotoSansCherokee-Regular.ttf [34032 bytes]
  NotoSansCoptic-Regular.ttf [20956 bytes]
  NotoSansDevanagari-Bold.ttf [119664 bytes]
  NotoSansDevanagari-Regular.ttf [123740 bytes]
  NotoSansDevanagariUI-Bold.ttf [114168 bytes]
  NotoSansDevanagariUI-Regular.ttf [119200 bytes]
  NotoSansEthiopic-Bold.ttf [142968 bytes]
  NotoSansEthiopic-Regular.ttf [142832 bytes]
  NotoSansGeorgian-Bold.ttf [19636 bytes]
  NotoSansGeorgian-Regular.ttf [19684 bytes]
  NotoSansGlagolitic-Regular.ttf [15272 bytes]
  NotoSansGujarati-Bold.ttf [116588 bytes]
  NotoSansGujarati-Regular.ttf [119608 bytes]
  NotoSansGujaratiUI-Bold.ttf [113872 bytes]
  NotoSansGujaratiUI-Regular.ttf [116948 bytes]
  NotoSansGurmukhi-Bold.ttf [31176 bytes]
  NotoSansGurmukhi-Regular.ttf [31336 bytes]
  NotoSansGurmukhiUI-Bold.ttf [31932 bytes]
  NotoSansGurmukhiUI-Regular.ttf [31692 bytes]
  NotoSansHans-Regular.otf [8154368 bytes]
  NotoSansHant-Regular.otf [3097576 bytes]
  NotoSansHanunoo-Regular.ttf [6340 bytes]
  NotoSansHebrew-Bold.ttf [16636 bytes]
  NotoSansHebrew-Regular.ttf [16456 bytes]
  NotoSansJP-Regular.otf [168304 bytes]
  NotoSansJavanese-Regular.ttf [32772 bytes]
  NotoSansKR-Regular.otf [1857184 bytes]
  NotoSansKannada-Bold.ttf [80016 bytes]
  NotoSansKannada-Regular.ttf [81392 bytes]
  NotoSansKannadaUI-Bold.ttf [79136 bytes]
  NotoSansKannadaUI-Regular.ttf [80644 bytes]
  NotoSansKayahLi-Regular.ttf [7540 bytes]
  NotoSansKhmer-Bold.ttf [33620 bytes]
  NotoSansKhmer-Regular.ttf [34612 bytes]
  NotoSansKhmerUI-Bold.ttf [36456 bytes]
  NotoSansKhmerUI-Regular.ttf [38160 bytes]
  NotoSansLao-Bold.ttf [29004 bytes]
  NotoSansLao-Regular.ttf [30352 bytes]
  NotoSansLaoUI-Bold.ttf [29064 bytes]
  NotoSansLaoUI-Regular.ttf [30372 bytes]
  NotoSansLepcha-Regular.ttf [101584 bytes]
  NotoSansLimbu-Regular.ttf [10700 bytes]
  NotoSansMalayalam-Bold.ttf [56740 bytes]
  NotoSansMalayalam-Regular.ttf [56864 bytes]
  NotoSansMalayalamUI-Bold.ttf [61124 bytes]
  NotoSansMalayalamUI-Regular.ttf [61360 bytes]
  NotoSansMeeteiMayek-Regular.ttf [13512 bytes]
  NotoSansMyanmar-Bold.ttf [104692 bytes]
  NotoSansMyanmar-Regular.ttf [107640 bytes]
  NotoSansMyanmarUI-Bold.ttf [94696 bytes]
  NotoSansMyanmarUI-Regular.ttf [94188 bytes]
  NotoSansOlChiki-Regular.ttf [7144 bytes]
  NotoSansRejang-Regular.ttf [6008 bytes]
  NotoSansSaurashtra-Regular.ttf [18296 bytes]
  NotoSansSinhala-Bold.ttf [148660 bytes]
  NotoSansSinhala-Regular.ttf [155876 bytes]
  NotoSansSundanese-Regular.ttf [10044 bytes]
  NotoSansSylotiNagri-Regular.ttf [14504 bytes]
  NotoSansSymbols-Regular-Subsetted.ttf [247940 bytes]
  NotoSansTagbanwa-Regular.ttf [5124 bytes]
  NotoSansTaiLe-Regular.ttf [8340 bytes]
  NotoSansTaiTham-Regular.ttf [46068 bytes]
  NotoSansTaiViet-Regular.ttf [15376 bytes]
  NotoSansTamil-Bold.ttf [33096 bytes]
  NotoSansTamil-Regular.ttf [32980 bytes]
  NotoSansTamilUI-Bold.ttf [33548 bytes]
  NotoSansTamilUI-Regular.ttf [33412 bytes]
  NotoSansTelugu-Bold.ttf [109936 bytes]
  NotoSansTelugu-Regular.ttf [110176 bytes]
  NotoSansTeluguUI-Bold.ttf [110240 bytes]
  NotoSansTeluguUI-Regular.ttf [110644 bytes]
  NotoSansThaana-Bold.ttf [14944 bytes]
  NotoSansThaana-Regular.ttf [13912 bytes]
  NotoSansThai-Bold.ttf [17484 bytes]
  NotoSansThai-Regular.ttf [20536 bytes]
  NotoSansThaiUI-Bold.ttf [18156 bytes]
  NotoSansThaiUI-Regular.ttf [21160 bytes]
  NotoSansTifinagh-Regular.ttf [13084 bytes]
  NotoSansYi-Regular.ttf [121148 bytes]
  NotoSerif-Bold.ttf [246688 bytes]
  NotoSerif-BoldItalic.ttf [261772 bytes]
  NotoSerif-Italic.ttf [248644 bytes]
  NotoSerif-Regular.ttf [245788 bytes]
  Roboto-Black.ttf [242172 bytes]
  Roboto-BlackItalic.ttf [263976 bytes]
  Roboto-Bold.ttf [242304 bytes]
  Roboto-BoldItalic.ttf [264068 bytes]
  Roboto-Italic.ttf [263056 bytes]
  Roboto-Light.ttf [243788 bytes]
  Roboto-LightItalic.ttf [266080 bytes]
  Roboto-Medium.ttf [241640 bytes]
  Roboto-MediumItalic.ttf [263548 bytes]
  Roboto-Regular.ttf [241008 bytes]
  Roboto-Thin.ttf [246428 bytes]
  Roboto-ThinItalic.ttf [267068 bytes]
  RobotoCondensed-Bold.ttf [239596 bytes]
  RobotoCondensed-BoldItalic.ttf [261660 bytes]
  RobotoCondensed-Italic.ttf [261992 bytes]
  RobotoCondensed-Light.ttf [240820 bytes]
  RobotoCondensed-LightItalic.ttf [264500 bytes]
  RobotoCondensed-Regular.ttf [238804 bytes]
  DroidSans-Bold.ttf [242304 bytes]
  DroidSans.ttf [241008 bytes]
*** Exceptions:
gm_mediacodec_dec: dalvik.system.PathClassLoader[DexPathList[[zip file "/data/app/com.gpac.Osmo4-1/base.apk"],nativeLibraryDirectories=[/data/app/com.gpac.Osmo4-1/lib/arm, /vendor/lib, /system/lib]]] couldn't find "libgm_mediacodec_dec.so"(class java.lang.UnsatisfiedLinkError)

**Comment by aureliendavid** [comment]
Hi, 

I don't have a device to test on at the moment but it looks like we're trying to load mediacodec as a module although it's now a filter. 

I fixed that in e0de5342 (apk at https://download.tsi.telecom-paristech.fr/gpac/new_builds/android/osmo4-1.0.0-rev57-ge0de5342-master.apk), can you try with that one and report back?

thanks

**Comment by SivanLiu** [comment]
> Hi,
> 
> I don't have a device to test on at the moment but it looks like we're trying to load mediacodec as a module although it's now a filter.
> 
> I fixed that in [e0de534](https://github.com/gpac/gpac/commit/e0de5342554f3b405a3ef0355c19341add5ba09e) (apk at https://download.tsi.telecom-paristech.fr/gpac/new_builds/android/osmo4-1.0.0-rev57-ge0de5342-master.apk), can you try with that one and report back?
> 
> thanks

![osmo4_log](https://user-images.githubusercontent.com/8191309/86072268-ca0d4100-bab3-11ea-80da-4ac8287b0483.jpg)


Thanks for your help. I have test the apk you gave me，load so is no error，but Osmor is loading continue， it seems to be stuck。

**Comment by aureliendavid** [comment]
I found a device to run some tests

I fixed the infinite loading (in https://download.tsi.telecom-paristech.fr/gpac/new_builds/android/osmo4-1.0.0-rev68-g7f0075eb-master.apk) but now the gui is not disaplying..

I'll keep looking

**Comment by SivanLiu** [comment]
I have test your apk，and is normal load libs， but the toast hint: “Error Filter mcdec missing process function - ignoring” is still show up。the gui display normally the next work。

On the other hand， I have found the sequential dependency of all so libs load may exist problemby "objdump -x xxoo.so | grep NEEDED"，and  the normal order is below:
![solibs load order](https://user-images.githubusercontent.com/8191309/86306690-821f2300-bc47-11ea-8aca-076b159af5f1.jpg)

It's just my personal understanding.Thanks.

**Comment by aureliendavid** [comment]
> I have test your apk，and is normal load libs， but the toast hint: “Error Filter mcdec missing process function - ignoring” is still show up。the gui display normally the next work。
> 

the toast should be just a warning and not important, i'll try to remove it

does the gui show up for you after that? can you screenshot it?

> On the other hand， I have found the sequential dependency of all so libs load may exist problemby "objdump -x xxoo.so | grep NEEDED"，and the normal order is below:
> ![solibs load order](https://user-images.githubusercontent.com/8191309/86306690-821f2300-bc47-11ea-8aca-076b159af5f1.jpg)

you shouldn't try to load gm_mediacodec_dec with v1.0.0 but otherwise i'll try to look into the order of the libs

**Comment by aureliendavid** [comment]
I pushed some changes that should make the warning about mcdec disappear and the gui should show up now. 

( https://download.tsi.telecom-paristech.fr/gpac/new_builds/android/osmo4-1.0.0-rev72-g8b1b8ecc-master.apk )

It's still terribly buggy unfortunately (mediacodec isn't working, on my device there's a crazy flicker that renders playback useless, etc.) but I won't be able to do much better for now. 

Contributions are very welcome :)

**Comment by SivanLiu** [comment]
> I pushed some changes that should make the warning about mcdec disappear and the gui should show up now.
> 
> ( https://download.tsi.telecom-paristech.fr/gpac/new_builds/android/osmo4-1.0.0-rev72-g8b1b8ecc-master.apk )
> 
> It's still terribly buggy unfortunately (mediacodec isn't working, on my device there's a crazy flicker that renders playback useless, etc.) but I won't be able to do much better for now.
> 
> Contributions are very welcome :)

I have tested your latest apk，the reuslt is the same as yours.(mediacodec isn't working, on my device there's a crazy flicker that renders playback useless, etc.)

**Comment by jeanlf** [comment]
rendering flicker is fixed and media codec should now work again, could you check it ?
There's still an issue with the "stop" button not responding properly on android, I'll investigate

**Comment by aureliendavid** [comment]
flickering is gone and mediacodec ok for me

(I still have audio skipping / stuttering but maybe that deserves a separate issue)

**Comment by SivanLiu** [comment]
> rendering flicker is fixed and media codec should now work again, could you check it ?
> There's still an issue with the "stop" button not responding properly on android, I'll investigate

Thanks for your help，I have checked the latested code，the rendering flicker and media codec work well at now.
"stop" not work normally，the log is below:
V/GPAC_WRAPPER: onMouseDown start
D/GPAC_WRAPPER: GPAC_EventProc() Message=119
I/GPAC_WRAPPER: Needs to display/hide the Virtual Keyboard (119)
V/GPAC_WRAPPER: Done showing virtual keyboard (119)
V/GPAC_WRAPPER: onMouseDown end
V/GPAC_WRAPPER: onMouseUp start
V/GPAC_WRAPPER: onMouseUp end
D/GPAC_WRAPPER: GPAC_EventProc() Message=110
V/GPAC_WRAPPER: onMouseDown start
V/GPAC_WRAPPER: onMouseDown end
V/GPAC_WRAPPER: onMouseUp start
V/GPAC_WRAPPER: onMouseUp end
V/GPAC_WRAPPER: onMouseDown start
V/GPAC_WRAPPER: onMouseDown end
V/GPAC_WRAPPER: onMouseUp start
V/GPAC_WRAPPER: onMouseUp end
V/GPAC_WRAPPER: onMouseDown start
V/GPAC_WRAPPER: onMouseDown end
V/GPAC_WRAPPER: onMouseUp start
V/GPAC_WRAPPER: onMouseUp end
V/GPAC_WRAPPER: onMouseDown start
V/GPAC_WRAPPER: onMouseDown end
V/GPAC_WRAPPER: onMouseUp start
V/GPAC_WRAPPER: onMouseUp end

**Comment by jeanlf** [comment]
latest git should now fix issues with stop freezing the GUI and mediacodec bugs with adaptive streaming, could you check it?

**Comment by SivanLiu** [comment]
> latest git should now fix issues with stop freezing the GUI and mediacodec bugs with adaptive streaming, could you check it?

yes, I checked it(osmo4-1.0.0-rev92-g0cb878dfb-master.apk) from the latest git source.
