### ISSUE TITLE
play speedly and online video error

### ISSUE THREAD

**Issue by SivanLiu** [gpac/gpac#1560]
Thanks for reporting your issue. Please make sure these boxes are checked before submitting your issue - thank you!

- [x] I looked for a similar issue and couldn't find any.
- [x] I tried with the latest version of GPAC. Installers available at http://gpac.io/downloads/gpac-nightly-builds/
- [x] I give enough information for contributors to reproduce my issue (meaningful title, github labels, platform and compiler, command-line ...). I can share files anonymously with this dropbox: https://www.mediafire.com/filedrop/filedrop_hosted.php?drop=eec9e058a9486fe4e99c33021481d9e1826ca9dbc242a6cfaab0fe95da5e5d95

Detailed guidelines: http://gpac.io/2013/07/16/how-to-file-a-bug-properly/
Hi,
1. when player video, drag the play progress bar,I found the GF_EVENT_QUALITY_SWITCHED not defined in the case

2020-01-01 18:43:09.482 13289-13345/com.gpac.Osmo4 E/GF_LOG_SCRIPT: [JS] 
2020-01-01 18:43:09.483 13289-13345/com.gpac.Osmo4 E/GF_LOG_SCRIPT: ReferenceError: GF_EVENT_QUALITY_SWITCHED is not defined
`2020-01-01 18:43:09.483 13289-13345/com.gpac.Osmo4 E/GF_LOG_SCRIPT:     at ext_filter_event (/data/data/com.gpac.Osmo4/share/gui/extensions/player/player.js:92)
        at <anonymous> (/data/data/com.gpac.Osmo4/share/gui/extensions/player/player.js:1109)
        at gwlib_filter_event (/data/data/com.gpac.Osmo4/share/gui/gwlib.js:952)
        at set_state (/data/data/com.gpac.Osmo4/share/gui/extensions/player/player.js:1323)
        at <anonymous> (/data/data/com.gpac.Osmo4/share/gui/extensions/player/player.js:570)
        at <anonymous> (/data/data/com.gpac.Osmo4/share/gui/gwlib.js:1857)`

2.the osmos client not support online video?I try (https://bitmovin.com/player-content/playhouse-vr/progressive.mp4) in the enter address  and it return open error.the log is below:
![image](https://user-images.githubusercontent.com/8191309/89012230-6beaac80-d344-11ea-8b73-25cbec92e5af.png)

`2020-01-01 18:53:32.644 14451-14580/com.gpac.Osmo4 E/GF_LOG_SCRIPT: [JS] 
2020-01-01 18:53:32.645 14451-14580/com.gpac.Osmo4 E/GF_LOG_SCRIPT: ReferenceError: GF_EVENT_QUALITY_SWITCHED is not defined
2020-01-01 18:53:32.646 14451-14580/com.gpac.Osmo4 E/GF_LOG_SCRIPT:     at ext_filter_event (/data/data/com.gpac.Osmo4/share/gui/extensions/player/player.js:92)
        at <anonymous> (/data/data/com.gpac.Osmo4/share/gui/extensions/player/player.js:1109)
        at gwlib_filter_event (/data/data/com.gpac.Osmo4/share/gui/gwlib.js:952)
        at <anonymous> (/data/data/com.gpac.Osmo4/share/gui/gwlib.js:2593)
        at <anonymous> (/data/data/com.gpac.Osmo4/share/gui/gwlib.js:2634)
        at <anonymous> (/data/data/com.gpac.Osmo4/share/gui/gwlib.js:106)
        at gw_close_child_list (/data/data/com.gpac.Osmo4/share/gui/gwlib.js:1159)
        at <anonymous> (/data/data/com.gpac.Osmo4/share/gui/gwlib.js:1630)
        at <anonymous> (/data/data/com.gpac.Osmo4/share/gui/gwlib.js:3033)
        at <anonymous> (/data/data/com.gpac.Osmo4/share/gui/gwlib.js:106)
        at <anonymous> (/data/data/com.gpac.Osmo4/share/gui/gwlib.js:1665)
        at apply (native)
        at <anonymous> (/data/data/com.gpac.Osmo4/share/gui/gwlib.js:388)
        at <anonymous> (/data/data/com.gpac.Osmo4/share/gui/gwlib.js:72)`

Thanks

**Comment by jeanlf** [comment]
this was a bug introduced yesterday, fixed this morning by 7e2a66b

**Comment by SivanLiu** [comment]
> this was a bug introduced yesterday, fixed this morning by [7e2a66b](https://github.com/gpac/gpac/commit/7e2a66bc46789dc10d905e5fd95d78b55dad77aa)

Thanks for your help
but the online video is also bad and the log is below:
`2020-01-01 18:15:29.886 19397-19437/com.gpac.Osmo4 E/GF_LOG_SCRIPT: [JS] 
2020-01-01 18:15:29.886 19397-19437/com.gpac.Osmo4 E/GF_LOG_SCRIPT: Throw 
2020-01-01 18:15:29.886 19397-19437/com.gpac.Osmo4 E/GF_LOG_SCRIPT: null
`

**Comment by jeanlf** [comment]
what do you mean "bad" ?

the JS error is now fixed

**Comment by SivanLiu** [comment]
> what do you mean "bad" ?
> 
> the JS error is now fixed
thanks for reply
I have tried the lastest osmos client just now,  but it still not open the online video?I try (https://bitmovin.com/player-content/playhouse-vr/progressive.mp4) in the enter address and it return open error.the log is below:
2020-01-01 18:15:29.886 19397-19437/com.gpac.Osmo4 E/GF_LOG_SCRIPT: [JS] 2020-01-01 18:15:29.886 19397-19437/com.gpac.Osmo4 E/GF_LOG_SCRIPT: Throw 2020-01-01 18:15:29.886 19397-19437/com.gpac.Osmo4 E/GF_LOG_SCRIPT: null

**Comment by jeanlf** [comment]
I think you have not the latest version, opening the file works (although here it takes some time) and no JS exception is throws. What is your OS and what is the version shwon by `gpac` ?

**Comment by SivanLiu** [comment]
> I think you have not the latest version, opening the file works (although here it takes some time) and no JS exception is throws. What is your OS and what is the version shwon by `gpac` ?

Sorry, I have tried the version before your last commit and I will test the latested version tomorrow.Thanks !

**Comment by SivanLiu** [comment]
> I think you have not the latest version, opening the file works (although here it takes some time) and no JS exception is throws. What is your OS and what is the version shwon by `gpac` ?

I have tested the lastest osmo4 client(osmo4-1.0.0-rev188-g2aa266dfa-master.apk),the result is the same as before.
Huawei Nexus 6p, Android 10, ROM:PixelExperience_angler

![image](https://user-images.githubusercontent.com/8191309/89116554-09221e00-d4c8-11ea-8ae9-dc366cb62d72.png)

![image](https://user-images.githubusercontent.com/8191309/89116552-fa3b6b80-d4c7-11ea-97e3-b6c64271c061.png)

and the log  is not error, it is below:
`2020-01-01 17:41:32.373 10360-10360/com.gpac.Osmo4 D/Osmo4GLSurfaceView: onKeyDown = 46
2020-01-01 17:41:32.375 10360-10360/com.gpac.Osmo4 D/Osmo4GLSurfaceView: onKeyUp =46
2020-01-01 17:41:32.377 10360-10360/com.gpac.Osmo4 D/Osmo4GLSurfaceView: onKeyDown = 43
2020-01-01 17:41:32.378 10360-10360/com.gpac.Osmo4 D/Osmo4GLSurfaceView: onKeyUp =43
2020-01-01 17:41:32.380 10360-10360/com.gpac.Osmo4 D/Osmo4GLSurfaceView: onKeyDown = 35
2020-01-01 17:41:32.382 10360-10360/com.gpac.Osmo4 D/Osmo4GLSurfaceView: onKeyUp =35
2020-01-01 17:41:32.384 10360-10360/com.gpac.Osmo4 D/Osmo4GLSurfaceView: onKeyDown = 46
2020-01-01 17:41:32.385 10360-10360/com.gpac.Osmo4 D/Osmo4GLSurfaceView: onKeyUp =46
2020-01-01 17:41:32.387 10360-10360/com.gpac.Osmo4 D/Osmo4GLSurfaceView: onKeyDown = 33
2020-01-01 17:41:32.389 10360-10360/com.gpac.Osmo4 D/Osmo4GLSurfaceView: onKeyUp =33
2020-01-01 17:41:32.393 10360-10360/com.gpac.Osmo4 D/Osmo4GLSurfaceView: onKeyDown = 47
2020-01-01 17:41:32.394 10360-10360/com.gpac.Osmo4 D/Osmo4GLSurfaceView: onKeyUp =47
2020-01-01 17:41:32.396 10360-10360/com.gpac.Osmo4 D/Osmo4GLSurfaceView: onKeyDown = 47
2020-01-01 17:41:32.398 10360-10360/com.gpac.Osmo4 D/Osmo4GLSurfaceView: onKeyUp =47
2020-01-01 17:41:32.399 10360-10360/com.gpac.Osmo4 D/Osmo4GLSurfaceView: onKeyDown = 37
2020-01-01 17:41:32.401 10360-10360/com.gpac.Osmo4 D/Osmo4GLSurfaceView: onKeyUp =37
2020-01-01 17:41:32.403 10360-10360/com.gpac.Osmo4 D/Osmo4GLSurfaceView: onKeyDown = 50
2020-01-01 17:41:32.405 10360-10360/com.gpac.Osmo4 D/Osmo4GLSurfaceView: onKeyUp =50
2020-01-01 17:41:32.406 10360-10403/com.gpac.Osmo4 V/GPAC_WRAPPER: onKeyPress start
2020-01-01 17:41:32.406 10360-10403/com.gpac.Osmo4 I/chatty: uid=10156(com.gpac.Osmo4) GLThread 97 identical 1 line
2020-01-01 17:41:32.406 10360-10403/com.gpac.Osmo4 V/GPAC_WRAPPER: onKeyPress start
2020-01-01 17:41:32.406 10360-10360/com.gpac.Osmo4 D/Osmo4GLSurfaceView: onKeyDown = 33
2020-01-01 17:41:32.406 10360-10403/com.gpac.Osmo4 V/GPAC_WRAPPER: onKeyPress start
2020-01-01 17:41:32.408 10360-10403/com.gpac.Osmo4 I/chatty: uid=10156(com.gpac.Osmo4) GLThread 97 identical 21 lines
2020-01-01 17:41:32.408 10360-10403/com.gpac.Osmo4 V/GPAC_WRAPPER: onKeyPress start
2020-01-01 17:41:32.408 10360-10360/com.gpac.Osmo4 D/Osmo4GLSurfaceView: onKeyUp =33
2020-01-01 17:41:32.410 10360-10360/com.gpac.Osmo4 D/Osmo4GLSurfaceView: onKeyDown = 56
2020-01-01 17:41:32.412 10360-10360/com.gpac.Osmo4 D/Osmo4GLSurfaceView: onKeyUp =56
2020-01-01 17:41:32.413 10360-10360/com.gpac.Osmo4 D/Osmo4GLSurfaceView: onKeyDown = 41
2020-01-01 17:41:32.415 10360-10360/com.gpac.Osmo4 D/Osmo4GLSurfaceView: onKeyUp =41
2020-01-01 17:41:32.417 10360-10360/com.gpac.Osmo4 D/Osmo4GLSurfaceView: onKeyDown = 44
2020-01-01 17:41:32.418 10360-10360/com.gpac.Osmo4 D/Osmo4GLSurfaceView: onKeyUp =44
2020-01-01 17:41:32.420 10360-10360/com.gpac.Osmo4 D/Osmo4GLSurfaceView: onKeyDown = 11
2020-01-01 17:41:32.422 10360-10360/com.gpac.Osmo4 D/Osmo4GLSurfaceView: onKeyUp =11
2020-01-01 17:41:32.454 10360-10403/com.gpac.Osmo4 V/GPAC_WRAPPER: onKeyPress start
2020-01-01 17:41:32.455 10360-10403/com.gpac.Osmo4 I/chatty: uid=10156(com.gpac.Osmo4) GLThread 97 identical 7 lines
2020-01-01 17:41:32.455 10360-10403/com.gpac.Osmo4 V/GPAC_WRAPPER: onKeyPress start
2020-01-01 17:41:33.573 10360-10360/com.gpac.Osmo4 D/Osmo4GLSurfaceView: onKeyDown = 66
2020-01-01 17:41:33.573 10360-10360/com.gpac.Osmo4 D/Osmo4GLSurfaceView: onKeyUp =66
2020-01-01 17:41:33.612 10360-10403/com.gpac.Osmo4 V/GPAC_WRAPPER: onKeyPress start
2020-01-01 17:41:33.612 10360-10403/com.gpac.Osmo4 V/GPAC_WRAPPER: onKeyPress start
2020-01-01 17:41:33.645 10360-10403/com.gpac.Osmo4 I/GPAC_WRAPPER: Needs to display/hide the Virtual Keyboard (117)
2020-01-01 17:41:33.646 10360-10403/com.gpac.Osmo4 V/GPAC_WRAPPER: Done showing virtual keyboard (117)
2020-01-01 17:41:33.664 10360-10403/com.gpac.Osmo4 V/GPAC_WRAPPER: GPAC_EventProc start
2020-01-01 17:41:33.664 10360-10403/com.gpac.Osmo4 V/GPAC_WRAPPER: Cannot find filter for service: Feature Not Supported
2020-01-01 17:41:33.664 10360-10403/com.gpac.Osmo4 V/GPAC_WRAPPER: GPAC_EventProc end`
