### ISSUE TITLE
Failed to build statically linked MP4Box

### ISSUE THREAD

**Issue by doktoil-makresh** [gpac/gpac#1685]
I'm trying to compile a static build of MP4Box by using the following:
`git clone https://github.com/gpac/gpac.git gpac
cd gpac
./configure --static-mp4box --enable-static-bin --use-zlib=no
make -j4`
However, the resulting MP4Box binary is still dynamically linked to some libraries:
` file bin/gcc/MP4Box
bin/gcc/MP4Box: ELF 64-bit LSB shared object, x86-64, version 1 (SYSV), dynamically linked, interpreter /lib64/ld-linux-x86-64.so.2, for GNU/Linux 3.2.0, BuildID[sha1]=116d5d167807300dc3c1685156e0d91dfa66783c, not stripped `
`ldd bin/gcc/MP4Box
	linux-vdso.so.1 (0x00007fff794af000)
	libm.so.6 => /lib/x86_64-linux-gnu/libm.so.6 (0x00007fa853c74000)
	libpthread.so.0 => /lib/x86_64-linux-gnu/libpthread.so.0 (0x00007fa853a55000)
	libdl.so.2 => /lib/x86_64-linux-gnu/libdl.so.2 (0x00007fa853851000)
	libc.so.6 => /lib/x86_64-linux-gnu/libc.so.6 (0x00007fa853460000)
	/lib64/ld-linux-x86-64.so.2 (0x00007fa854a25000)`

I'm trying on a Ubuntu 18.04.5, with GNU make 4.1
I had to manually edit config.mak file and add "-static" at the end of LDFLAGS variable.
This raises few errors:
`../../bin/gcc/libgpac_static.a(vrml_js.o): In function `qjs_module_loader':
vrml_js.c:(.text+0x7bc1): warning: Using 'dlopen' in statically linked applications requires at runtime the shared libraries from the glibc version used for linking
../../bin/gcc/libgpac_static.a(os_net.o): In function `gf_sk_get_ipv6_addr':
os_net.c:(.text+0x98): warning: Using 'getaddrinfo' in statically linked applications requires at runtime the shared libraries from the glibc version used for linking
make[2]: Leaving directory '/home/user/git/gpac/applications/gpac'
make[2]: Entering directory '/home/user/git/gpac/applications/mp4box'
../../bin/gcc/libgpac_static.a(dec_nvdec_sdk.o): In function `cuInit':
dec_nvdec_sdk.c:(.text+0xc2): warning: Using 'dlopen' in statically linked applications requires at runtime the shared libraries from the glibc version used for linking
../../bin/gcc/libgpac_static.a(os_net.o): In function `gf_sk_get_ipv6_addr':
os_net.c:(.text+0x98): warning: Using 'getaddrinfo' in statically linked applications requires at runtime the shared libraries from the glibc version used for linking`

But now, the MP4Box binary is statically linked:
`bin/gcc/MP4Box: ELF 64-bit LSB executable, x86-64, version 1 (GNU/Linux), statically linked, for GNU/Linux 3.2.0, BuildID[sha1]=159d1b7f87feca3a55747995fb655244cb596819, with debug_info, not stripped`

- [X] I looked for a similar issue and couldn't find any.
- [X] I tried with the latest version of GPAC. Installers available at http://gpac.io/downloads/gpac-nightly-builds/
- [ ] I give enough information for contributors to reproduce my issue (meaningful title, github labels, platform and compiler, command-line ...). I can share files anonymously with this dropbox: https://www.mediafire.com/filedrop/filedrop_hosted.php?drop=eec9e058a9486fe4e99c33021481d9e1826ca9dbc242a6cfaab0fe95da5e5d95

Detailed guidelines: http://gpac.io/2013/07/16/how-to-file-a-bug-properly/

**Comment by rbouqueau** [comment]
I confirm that our static build:

```
superu@ubuntu1804:~/gpac$ ldd bin/gcc/MP4Box
        linux-vdso.so.1 (0x00007fffa7bb3000)
        libm.so.6 => /lib/x86_64-linux-gnu/libm.so.6 (0x00007f02ce318000)
        libX11.so.6 => /usr/lib/x86_64-linux-gnu/libX11.so.6 (0x00007f02cdfe0000)
        libXext.so.6 => /usr/lib/x86_64-linux-gnu/libXext.so.6 (0x00007f02cddce000)
        libpthread.so.0 => /lib/x86_64-linux-gnu/libpthread.so.0 (0x00007f02cdbaf000)
        libdl.so.2 => /lib/x86_64-linux-gnu/libdl.so.2 (0x00007f02cd9ab000)
        libc.so.6 => /lib/x86_64-linux-gnu/libc.so.6 (0x00007f02cd5ba000)
        /lib64/ld-linux-x86-64.so.2 (0x00007f02cf084000)
        libxcb.so.1 => /usr/lib/x86_64-linux-gnu/libxcb.so.1 (0x00007f02cd392000)
        libXau.so.6 => /usr/lib/x86_64-linux-gnu/libXau.so.6 (0x00007f02cd18e000)
        libXdmcp.so.6 => /usr/lib/x86_64-linux-gnu/libXdmcp.so.6 (0x00007f02ccf88000)
        libbsd.so.0 => /lib/x86_64-linux-gnu/libbsd.so.0 (0x00007f02ccd73000)
        librt.so.1 => /lib/x86_64-linux-gnu/librt.so.1 (0x00007f02ccb6b000)
```

@doktoil-makresh 'static' means several things. What kind of executable do you plan to build?

**Comment by doktoil-makresh** [comment]
My goal is to have an independent binary (not dynamically linked to external libraries). Then I can use this binary on a Linux system without the need to install something else.

**Comment by rbouqueau** [comment]
Ok but what is an external library for you? For example in your ```ldd``` output: ```ldd bin/gcc/MP4Box linux-vdso.so.1 (0x00007fff794af000) libm.so.6 => /lib/x86_64-linux-gnu/libm.so.6 (0x00007fa853c74000) libpthread.so.0 => /lib/x86_64-linux-gnu/libpthread.so.0 (0x00007fa853a55000) libdl.so.2 => /lib/x86_64-linux-gnu/libdl.so.2 (0x00007fa853851000) libc.so.6 => /lib/x86_64-linux-gnu/libc.so.6 (0x00007fa853460000) /lib64/ld-linux-x86-64.so.2 (0x00007fa854a25000)```, what would you like to be removed?

**Comment by doktoil-makresh** [comment]
I wanted to remove the dependency to libm, not present on AWS Lambda (serveless)
If I add the -static to the LDFLAGS variable in config.mak file I get this result:
`ldd gcc/bin/MP4Box 
	not a dynamic executable`
Which is clearly not the same as yours.

**Comment by rbouqueau** [comment]
Thans for the additional info. I won't take any decision alone on this but I want to document.

```--static-mp4box --enable-static-bin --use-zlib=no```:
```
8279864 gpac
15158484 libgpac_static.a
8732800 MP4Box
```

```--static-mp4box --enable-static-bin --use-zlib=no --strip```:
```
8279808 gpac
15155436 libgpac_static.a
8732744 MP4Box
```
=> marginal gain

```./configure --enable-static-bin --use-zlib=no --use-png=no --use-ft=no --disable-ssl --disable-vrml ... --extra-ldflags=-static --strip```
```
8279808 gpac
15155436 libgpac_static.a
8732744 MP4Box
```
Note1: I had to disable "x11". There should be a flag to either import them statically (pkg-config - check themselves have no dynamic dependencies -> or use an external script (e.g. zenbuild) to build our dependencies) or disable extras for now.
Note2: scenegraph/vrml_js calls dlopen() which generates this warning: ```warning: Using 'dlopen' in statically linked applications requires at runtime the shared libraries from the glibc version used for linking```. Removing it proved impossible because we don't build with all the 'disable-xx' configurations.

@jeanlf @aureliendavid What's your opinion on how to progress here?

**Comment by jeanlf** [comment]
did a bit of cleanup:
```./configure --static-bin```

(old `--static-mp4box` still recognized for the moment).

This should give you a clean static, no deps MP4Box and gpac on linux (not possible on OSX, not yet working on windows, not sure we'll ever add this).

This will disable a few things, namely:
- openssl (dependency of libcrypto on dlopen)
- ipv6 
- IPv4 DNS lookup
- openGL
- all audio/video outputs
- a few codecs (and all ffmpeg support)
- dynamic loading of QuickJS modules

Could you please test ?

**Comment by Patman86** [comment]
I get an error when I try to compile MP4Box with MSYS2 / MinGW. Here is my log-file
[config.log](https://github.com/gpac/gpac/files/6070410/config.log)

**Comment by jeanlf** [comment]
could you post the make error (config.log only reports library detection failures) ?

And as said previously, `-static-bin` on windows is not completely working yet, there's still a bunch of dependencies on msys2 dlls...

**Comment by Patman86** [comment]
Here is the make error:

```
make[1]: Leaving directory '/h/repos/gpac/src'
make -C applications all
make[1]: Entering directory '/h/repos/gpac/applications'
set -e; for i in gpac mp4box  ; do make -C $i all; done
make[2]: Entering directory '/h/repos/gpac/applications/gpac'
  CC main.c
  RC /h/repos/gpac/manifest.rc
windres /h/repos/gpac/manifest.rc -o /h/repos/gpac/manifest.o
H:/mabs/msys64/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/10.2.0/../../../../x86_64-w64-mingw32/bin/ld.exe: ../../bin/gcc/libgpac_static.a(downloader.o):downloader.c:(.text+0x1487): undefined reference to `__imp_nghttp2_session_del'
H:/mabs/msys64/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/10.2.0/../../../../x86_64-w64-mingw32/bin/ld.exe: ../../bin/gcc/libgpac_static.a(downloader.o):downloader.c:(.text+0x2522): undefined reference to `__imp_nghttp2_strerror'
H:/mabs/msys64/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/10.2.0/../../../../x86_64-w64-mingw32/bin/ld.exe: ../../bin/gcc/libgpac_static.a(downloader.o):downloader.c:(.text+0x2529): undefined reference to `__imp_nghttp2_session_send'
H:/mabs/msys64/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/10.2.0/../../../../x86_64-w64-mingw32/bin/ld.exe: ../../bin/gcc/libgpac_static.a(downloader.o):downloader.c:(.text+0x261d): undefined reference to `__imp_nghttp2_session_mem_recv'
H:/mabs/msys64/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/10.2.0/../../../../x86_64-w64-mingw32/bin/ld.exe: ../../bin/gcc/libgpac_static.a(downloader.o):downloader.c:(.text+0x27bd): undefined reference to `__imp_nghttp2_strerror'
H:/mabs/msys64/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/10.2.0/../../../../x86_64-w64-mingw32/bin/ld.exe: ../../bin/gcc/libgpac_static.a(downloader.o):downloader.c:(.text+0x285a): undefined reference to `__imp_nghttp2_session_send'
H:/mabs/msys64/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/10.2.0/../../../../x86_64-w64-mingw32/bin/ld.exe: ../../bin/gcc/libgpac_static.a(downloader.o):downloader.c:(.text+0x288d): undefined reference to `__imp_nghttp2_session_mem_recv'
H:/mabs/msys64/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/10.2.0/../../../../x86_64-w64-mingw32/bin/ld.exe: ../../bin/gcc/libgpac_static.a(downloader.o):downloader.c:(.text+0x291b): undefined reference to `__imp_nghttp2_strerror'
H:/mabs/msys64/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/10.2.0/../../../../x86_64-w64-mingw32/bin/ld.exe: ../../bin/gcc/libgpac_static.a(downloader.o):downloader.c:(.text+0x29a1): undefined reference to `__imp_nghttp2_strerror'
H:/mabs/msys64/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/10.2.0/../../../../x86_64-w64-mingw32/bin/ld.exe: ../../bin/gcc/libgpac_static.a(downloader.o):downloader.c:(.text+0x2a44): undefined reference to `__imp_nghttp2_session_send'
H:/mabs/msys64/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/10.2.0/../../../../x86_64-w64-mingw32/bin/ld.exe: ../../bin/gcc/libgpac_static.a(downloader.o):downloader.c:(.text+0x2aa5): undefined reference to `__imp_nghttp2_session_mem_recv'
H:/mabs/msys64/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/10.2.0/../../../../x86_64-w64-mingw32/bin/ld.exe: ../../bin/gcc/libgpac_static.a(downloader.o):downloader.c:(.text+0x2b4c): undefined reference to `__imp_nghttp2_strerror'
H:/mabs/msys64/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/10.2.0/../../../../x86_64-w64-mingw32/bin/ld.exe: ../../bin/gcc/libgpac_static.a(downloader.o):downloader.c:(.text+0x2bb8): undefined reference to `__imp_nghttp2_strerror'
H:/mabs/msys64/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/10.2.0/../../../../x86_64-w64-mingw32/bin/ld.exe: ../../bin/gcc/libgpac_static.a(downloader.o):downloader.c:(.text+0x2bfd): undefined reference to `__imp_nghttp2_session_callbacks_new'
H:/mabs/msys64/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/10.2.0/../../../../x86_64-w64-mingw32/bin/ld.exe: ../../bin/gcc/libgpac_static.a(downloader.o):downloader.c:(.text+0x2c0f): undefined reference to `__imp_nghttp2_session_callbacks_set_send_callback'
H:/mabs/msys64/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/10.2.0/../../../../x86_64-w64-mingw32/bin/ld.exe: ../../bin/gcc/libgpac_static.a(downloader.o):downloader.c:(.text+0x2c21): undefined reference to `__imp_nghttp2_session_callbacks_set_on_frame_recv_callback'
H:/mabs/msys64/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/10.2.0/../../../../x86_64-w64-mingw32/bin/ld.exe: ../../bin/gcc/libgpac_static.a(downloader.o):downloader.c:(.text+0x2c33): undefined reference to `__imp_nghttp2_session_callbacks_set_before_frame_send_callback'
H:/mabs/msys64/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/10.2.0/../../../../x86_64-w64-mingw32/bin/ld.exe: ../../bin/gcc/libgpac_static.a(downloader.o):downloader.c:(.text+0x2c45): undefined reference to `__imp_nghttp2_session_callbacks_set_on_data_chunk_recv_callback'
H:/mabs/msys64/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/10.2.0/../../../../x86_64-w64-mingw32/bin/ld.exe: ../../bin/gcc/libgpac_static.a(downloader.o):downloader.c:(.text+0x2c57): undefined reference to `__imp_nghttp2_session_callbacks_set_on_stream_close_callback'
H:/mabs/msys64/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/10.2.0/../../../../x86_64-w64-mingw32/bin/ld.exe: ../../bin/gcc/libgpac_static.a(downloader.o):downloader.c:(.text+0x2c69): undefined reference to `__imp_nghttp2_session_callbacks_set_on_header_callback'
H:/mabs/msys64/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/10.2.0/../../../../x86_64-w64-mingw32/bin/ld.exe: ../../bin/gcc/libgpac_static.a(downloader.o):downloader.c:(.text+0x2c7b): undefined reference to `__imp_nghttp2_session_callbacks_set_on_begin_headers_callback'
H:/mabs/msys64/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/10.2.0/../../../../x86_64-w64-mingw32/bin/ld.exe: ../../bin/gcc/libgpac_static.a(downloader.o):downloader.c:(.text+0x2c8d): undefined reference to `__imp_nghttp2_session_callbacks_set_error_callback'
H:/mabs/msys64/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/10.2.0/../../../../x86_64-w64-mingw32/bin/ld.exe: ../../bin/gcc/libgpac_static.a(downloader.o):downloader.c:(.text+0x2d35): undefined reference to `__imp_nghttp2_session_server_new'
H:/mabs/msys64/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/10.2.0/../../../../x86_64-w64-mingw32/bin/ld.exe: ../../bin/gcc/libgpac_static.a(downloader.o):downloader.c:(.text+0x2d45): undefined reference to `__imp_nghttp2_session_callbacks_del'
H:/mabs/msys64/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/10.2.0/../../../../x86_64-w64-mingw32/bin/ld.exe: ../../bin/gcc/libgpac_static.a(downloader.o):downloader.c:(.text+0x2df3): undefined reference to `__imp_nghttp2_session_upgrade2'
H:/mabs/msys64/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/10.2.0/../../../../x86_64-w64-mingw32/bin/ld.exe: ../../bin/gcc/libgpac_static.a(downloader.o):downloader.c:(.text+0x2e32): undefined reference to `__imp_nghttp2_submit_settings'
H:/mabs/msys64/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/10.2.0/../../../../x86_64-w64-mingw32/bin/ld.exe: ../../bin/gcc/libgpac_static.a(downloader.o):downloader.c:(.text+0x2e7d): undefined reference to `__imp_nghttp2_session_send'
H:/mabs/msys64/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/10.2.0/../../../../x86_64-w64-mingw32/bin/ld.exe: ../../bin/gcc/libgpac_static.a(downloader.o):downloader.c:(.text+0x2ed2): undefined reference to `__imp_nghttp2_session_client_new'
H:/mabs/msys64/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/10.2.0/../../../../x86_64-w64-mingw32/bin/ld.exe: ../../bin/gcc/libgpac_static.a(downloader.o):downloader.c:(.text+0x2eee): undefined reference to `__imp_nghttp2_session_callbacks_set_send_data_callback'
H:/mabs/msys64/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/10.2.0/../../../../x86_64-w64-mingw32/bin/ld.exe: ../../bin/gcc/libgpac_static.a(downloader.o):downloader.c:(.text+0x2f43): undefined reference to `__imp_nghttp2_strerror'
H:/mabs/msys64/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/10.2.0/../../../../x86_64-w64-mingw32/bin/ld.exe: ../../bin/gcc/libgpac_static.a(downloader.o):downloader.c:(.text+0x3e8a): undefined reference to `__imp_nghttp2_submit_request'
H:/mabs/msys64/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/10.2.0/../../../../x86_64-w64-mingw32/bin/ld.exe: ../../bin/gcc/libgpac_static.a(downloader.o):downloader.c:(.text+0x3f08): undefined reference to `__imp_nghttp2_session_send'
H:/mabs/msys64/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/10.2.0/../../../../x86_64-w64-mingw32/bin/ld.exe: ../../bin/gcc/libgpac_static.a(downloader.o):downloader.c:(.text+0x484c): undefined reference to `__imp_nghttp2_pack_settings_payload'
H:/mabs/msys64/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/10.2.0/../../../../x86_64-w64-mingw32/bin/ld.exe: ../../bin/gcc/libgpac_static.a(downloader.o):downloader.c:(.text+0x49f0): undefined reference to `__imp_nghttp2_strerror'
H:/mabs/msys64/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/10.2.0/../../../../x86_64-w64-mingw32/bin/ld.exe: ../../bin/gcc/libgpac_static.a(downloader.o):downloader.c:(.text+0x5bc6): undefined reference to `__imp_nghttp2_submit_response'
H:/mabs/msys64/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/10.2.0/../../../../x86_64-w64-mingw32/bin/ld.exe: ../../bin/gcc/libgpac_static.a(downloader.o):downloader.c:(.text+0x5beb): undefined reference to `__imp_nghttp2_session_send'
H:/mabs/msys64/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/10.2.0/../../../../x86_64-w64-mingw32/bin/ld.exe: ../../bin/gcc/libgpac_static.a(downloader.o):downloader.c:(.text+0x5f07): undefined reference to `__imp_nghttp2_strerror'
H:/mabs/msys64/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/10.2.0/../../../../x86_64-w64-mingw32/bin/ld.exe: ../../bin/gcc/libgpac_static.a(downloader.o):downloader.c:(.text+0x6052): undefined reference to `__imp_nghttp2_strerror'
H:/mabs/msys64/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/10.2.0/../../../../x86_64-w64-mingw32/bin/ld.exe: ../../bin/gcc/libgpac_static.a(downloader.o):downloader.c:(.text+0x8ba1): undefined reference to `__imp_nghttp2_pack_settings_payload'
H:/mabs/msys64/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/10.2.0/../../../../x86_64-w64-mingw32/bin/ld.exe: ../../bin/gcc/libgpac_static.a(downloader.o):downloader.c:(.text+0x8be3): undefined reference to `__imp_nghttp2_session_upgrade2'
H:/mabs/msys64/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/10.2.0/../../../../x86_64-w64-mingw32/bin/ld.exe: ../../bin/gcc/libgpac_static.a(downloader.o):downloader.c:(.text+0x8c12): undefined reference to `__imp_nghttp2_session_mem_recv'
H:/mabs/msys64/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/10.2.0/../../../../x86_64-w64-mingw32/bin/ld.exe: ../../bin/gcc/libgpac_static.a(downloader.o):downloader.c:(.text+0x8c67): undefined reference to `__imp_nghttp2_session_send'
H:/mabs/msys64/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/10.2.0/../../../../x86_64-w64-mingw32/bin/ld.exe: ../../bin/gcc/libgpac_static.a(downloader.o):downloader.c:(.text+0x9cde): undefined reference to `__imp_nghttp2_strerror'
H:/mabs/msys64/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/10.2.0/../../../../x86_64-w64-mingw32/bin/ld.exe: ../../bin/gcc/libgpac_static.a(downloader.o):downloader.c:(.text+0x9df7): undefined reference to `__imp_nghttp2_strerror'
H:/mabs/msys64/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/10.2.0/../../../../x86_64-w64-mingw32/bin/ld.exe: ../../bin/gcc/libgpac_static.a(downloader.o):downloader.c:(.text+0xa431): undefined reference to `__imp_nghttp2_strerror'
H:/mabs/msys64/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/10.2.0/../../../../x86_64-w64-mingw32/bin/ld.exe: ../../bin/gcc/libgpac_static.a(downloader.o):downloader.c:(.text+0xc415): undefined reference to `__imp_nghttp2_session_send'
H:/mabs/msys64/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/10.2.0/../../../../x86_64-w64-mingw32/bin/ld.exe: ../../bin/gcc/libgpac_static.a(downloader.o):downloader.c:(.text+0xc491): undefined reference to `__imp_nghttp2_strerror'
H:/mabs/msys64/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/10.2.0/../../../../x86_64-w64-mingw32/bin/ld.exe: ../../bin/gcc/libgpac_static.a(downloader.o):downloader.c:(.text+0xcd76): undefined reference to `__imp_nghttp2_session_send'
H:/mabs/msys64/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/10.2.0/../../../../x86_64-w64-mingw32/bin/ld.exe: ../../bin/gcc/libgpac_static.a(downloader.o):downloader.c:(.text+0xd154): undefined reference to `__imp_nghttp2_strerror'
H:/mabs/msys64/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/10.2.0/../../../../x86_64-w64-mingw32/bin/ld.exe: ../../bin/gcc/libgpac_static.a(downloader.o):downloader.c:(.text+0xd402): undefined reference to `__imp_nghttp2_submit_rst_stream'
H:/mabs/msys64/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/10.2.0/../../../../x86_64-w64-mingw32/bin/ld.exe: ../../bin/gcc/libgpac_static.a(downloader.o):downloader.c:(.text+0xd413): undefined reference to `__imp_nghttp2_session_send'
H:/mabs/msys64/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/10.2.0/../../../../x86_64-w64-mingw32/bin/ld.exe: ../../bin/gcc/libgpac_static.a(downloader.o):downloader.c:(.text+0xd52c): undefined reference to `__imp_nghttp2_strerror'
H:/mabs/msys64/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/10.2.0/../../../../x86_64-w64-mingw32/bin/ld.exe: ../../bin/gcc/libgpac_static.a(downloader.o):downloader.c:(.text+0xde41): undefined reference to `__imp_nghttp2_session_send'
H:/mabs/msys64/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/10.2.0/../../../../x86_64-w64-mingw32/bin/ld.exe: ../../bin/gcc/libgpac_static.a(downloader.o):downloader.c:(.text+0xdf0c): undefined reference to `__imp_nghttp2_session_resume_data'
H:/mabs/msys64/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/10.2.0/../../../../x86_64-w64-mingw32/bin/ld.exe: ../../bin/gcc/libgpac_static.a(downloader.o):downloader.c:(.text+0xdfa3): undefined reference to `__imp_nghttp2_strerror'
H:/mabs/msys64/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/10.2.0/../../../../x86_64-w64-mingw32/bin/ld.exe: ../../bin/gcc/libgpac_static.a(downloader.o):downloader.c:(.text+0xdfe8): undefined reference to `__imp_nghttp2_session_want_read'
H:/mabs/msys64/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/10.2.0/../../../../x86_64-w64-mingw32/bin/ld.exe: ../../bin/gcc/libgpac_static.a(downloader.o):downloader.c:(.text+0xdfef): undefined reference to `__imp_nghttp2_session_send'
H:/mabs/msys64/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/10.2.0/../../../../x86_64-w64-mingw32/bin/ld.exe: ../../bin/gcc/libgpac_static.a(downloader.o):downloader.c:(.text+0xdff6): undefined reference to `__imp_nghttp2_session_mem_recv'
H:/mabs/msys64/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/10.2.0/../../../../x86_64-w64-mingw32/bin/ld.exe: ../../bin/gcc/libgpac_static.a(downloader.o):downloader.c:(.text+0xe15c): undefined reference to `__imp_nghttp2_strerror'
H:/mabs/msys64/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/10.2.0/../../../../x86_64-w64-mingw32/bin/ld.exe: ../../bin/gcc/libgpac_static.a(downloader.o):downloader.c:(.text+0xe1d1): undefined reference to `__imp_nghttp2_strerror'
H:/mabs/msys64/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/10.2.0/../../../../x86_64-w64-mingw32/bin/ld.exe: H:/mabs/msys64/mingw64/lib/../lib/libpng.a(png.o):(.text+0x1410): undefined reference to `crc32'
H:/mabs/msys64/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/10.2.0/../../../../x86_64-w64-mingw32/bin/ld.exe: H:/mabs/msys64/mingw64/lib/../lib/libpng.a(png.o):(.text+0x1488): undefined reference to `crc32'
H:/mabs/msys64/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/10.2.0/../../../../x86_64-w64-mingw32/bin/ld.exe: H:/mabs/msys64/mingw64/lib/../lib/libpng.a(png.o):(.text+0x27f7): undefined reference to `adler32'
H:/mabs/msys64/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/10.2.0/../../../../x86_64-w64-mingw32/bin/ld.exe: H:/mabs/msys64/mingw64/lib/../lib/libpng.a(png.o):(.text+0x2804): undefined reference to `adler32'
H:/mabs/msys64/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/10.2.0/../../../../x86_64-w64-mingw32/bin/ld.exe: H:/mabs/msys64/mingw64/lib/../lib/libpng.a(png.o):(.text+0x2815): undefined reference to `crc32'
H:/mabs/msys64/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/10.2.0/../../../../x86_64-w64-mingw32/bin/ld.exe: H:/mabs/msys64/mingw64/lib/../lib/libpng.a(png.o):(.text+0x2822): undefined reference to `crc32'
H:/mabs/msys64/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/10.2.0/../../../../x86_64-w64-mingw32/bin/ld.exe: H:/mabs/msys64/mingw64/lib/../lib/libpng.a(png.o):(.text+0x1c7d): undefined reference to `inflateReset'
H:/mabs/msys64/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/10.2.0/../../../../x86_64-w64-mingw32/bin/ld.exe: H:/mabs/msys64/mingw64/lib/../lib/libpng.a(pngread.o):(.text+0x48cd): undefined reference to `inflateEnd'
H:/mabs/msys64/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/10.2.0/../../../../x86_64-w64-mingw32/bin/ld.exe: H:/mabs/msys64/mingw64/lib/../lib/libpng.a(pngrutil.o):(.text+0x2e5): undefined reference to `inflateReset2'
H:/mabs/msys64/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/10.2.0/../../../../x86_64-w64-mingw32/bin/ld.exe: H:/mabs/msys64/mingw64/lib/../lib/libpng.a(pngrutil.o):(.text+0x351): undefined reference to `inflateInit2_'
H:/mabs/msys64/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/10.2.0/../../../../x86_64-w64-mingw32/bin/ld.exe: H:/mabs/msys64/mingw64/lib/../lib/libpng.a(pngrutil.o):(.text+0x374): undefined reference to `inflateValidate'
H:/mabs/msys64/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/10.2.0/../../../../x86_64-w64-mingw32/bin/ld.exe: H:/mabs/msys64/mingw64/lib/../lib/libpng.a(pngrutil.o):(.text+0xbb8): undefined reference to `inflateReset'
H:/mabs/msys64/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/10.2.0/../../../../x86_64-w64-mingw32/bin/ld.exe: H:/mabs/msys64/mingw64/lib/../lib/libpng.a(pngrutil.o):(.text+0x59f0): undefined reference to `inflateReset'
H:/mabs/msys64/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/10.2.0/../../../../x86_64-w64-mingw32/bin/ld.exe: H:/mabs/msys64/mingw64/lib/../lib/libpng.a(pngrutil.o):(.text+0x91e): undefined reference to `inflate'
H:/mabs/msys64/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/10.2.0/../../../../x86_64-w64-mingw32/bin/ld.exe: H:/mabs/msys64/mingw64/lib/../lib/libpng.a(pngwrite.o):(.text+0x1ce8): undefined reference to `deflateEnd'
H:/mabs/msys64/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/10.2.0/../../../../x86_64-w64-mingw32/bin/ld.exe: H:/mabs/msys64/mingw64/lib/../lib/libpng.a(pngwutil.o):(.text+0x265): undefined reference to `deflateEnd'
H:/mabs/msys64/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/10.2.0/../../../../x86_64-w64-mingw32/bin/ld.exe: H:/mabs/msys64/mingw64/lib/../lib/libpng.a(pngwutil.o):(.text+0x2cd): undefined reference to `deflateInit2_'
H:/mabs/msys64/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/10.2.0/../../../../x86_64-w64-mingw32/bin/ld.exe: H:/mabs/msys64/mingw64/lib/../lib/libpng.a(pngwutil.o):(.text+0x344): undefined reference to `deflateReset'
H:/mabs/msys64/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/10.2.0/../../../../x86_64-w64-mingw32/bin/ld.exe: H:/mabs/msys64/mingw64/lib/../lib/libpng.a(pngwutil.o):(.text+0x59a): undefined reference to `deflate'
H:/mabs/msys64/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/10.2.0/../../../../x86_64-w64-mingw32/bin/ld.exe: H:/mabs/msys64/mingw64/lib/../lib/libpng.a(pngwutil.o):(.text+0x2545): undefined reference to `deflate'
collect2.exe: error: ld returned 1 exit status
make[2]: *** [Makefile:56: gpac.exe] Error 1
make[2]: Leaving directory '/h/repos/gpac/applications/gpac'
make[1]: *** [Makefile:41: apps] Error 2
make[1]: Leaving directory '/h/repos/gpac/applications'
make: *** [Makefile:14: all] Error 2
```

**Comment by aureliendavid** [comment]
@Patman86 : can you retry with the latest commit?

I think I fixed some cases, hopefully without breaking anything else

**Comment by Patman86** [comment]
Thank you for your efforts, but the error still persists. I get an identical error message.

**Comment by aureliendavid** [comment]
really the exact same thing after updating to 75b879f ?

I just tried it on a fresh clone: 

```
git clone https://github.com/gpac/gpac.git
make clean ; ./configure --static-bin --use-zlib=no  ; make -j8 
```

and it worked.

Can you post the output of your configure? not the config.log but just the stdout output that looks like this for me: 

```
** System Configuration
Install prefix: /usr/local
Source path: /c/Users/adavid/dev/gpac/mingw/newgpac
C   compiler: gcc
C++ compiler: g++
make: make
CPU: x86_64
Big Endian: no

** GPAC 1.1.0-DEV rev542-g75b879fc4-master Core Configuration **
Static binaries enabled
debug version: no
GProf enabled: no
Memory tracking enabled: no
Sanitizer enabled: no
Fixed-Point Version: no
IPV6 Support: no
QuickJS Support: yes

** Detected libraries **
zlib: force-no
OpenGL support: no
TinyGL support: no
OpenSSL support: no
SDL: no
DirectX: no
FreeType: no
JPEG: no
OpenJPEG: no
PNG: no
MAD: no
FAAD: no
XVID: no
FFMPEG: no
LZMA: no
Xiph OGG: no
Platinum UPnP: no
A52 (AC3): no
OpenSVCDecoder: no
OpenHEVCDecoder: no
Freenect: no
nghttp2: system
```

**Comment by Patman86** [comment]
Now I've tried a fresh clone and it worked. There must have been something strange in the folder ...
thx @ all
