### ISSUE TITLE
[bug]  gpac input hls stream report error

### ISSUE THREAD

**Issue by fastfading** [gpac/gpac#1996]
Thanks for reporting your issue. Please make sure these boxes are checked before submitting your issue - thank you!

- [yes ] I looked for a similar issue and couldn't find any.
- [master release ] I tried with the latest version of GPAC. Installers available at http://gpac.io/downloads/gpac-nightly-builds/
- [yes ] I give enough information for contributors to reproduce my issue (meaningful title, github labels, platform and compiler, command-line ...). I can share files anonymously with this dropbox: https://www.mediafire.com/filedrop/filedrop_hosted.php?drop=eec9e058a9486fe4e99c33021481d9e1826ca9dbc242a6cfaab0fe95da5e5d95

Detailed guidelines: http://gpac.io/2013/07/16/how-to-file-a-bug-properly/

I try to input a hls stream , 
/opt/git/gpac/bin/gcc/gpac -i http://10.140.200.254:9091/abc.m3u8 -o arch.mp4
it reports  
[DASH] Error in downloading new segment http://10.140.200.254:9091/abc/abc/1639646434.ts: Requested URL is not valid or cannot be found - waited 1188 ms but segment still not available, checking next one ...

file structure  and m3u8 file
![image](https://user-images.githubusercontent.com/8351732/146476158-42fb6a8c-f6ba-4f50-922a-64653296ecc1.png)
![image](https://user-images.githubusercontent.com/8351732/146476198-4da606bc-c2a3-4cf3-bd10-1ded501563cd.png)
this is play well in all hls browser

but in gpac    it add two  "abc"  prefix 
http://10.140.200.254:9091/abc/abc/1639646434.ts

**Comment by fastfading** [comment]
and the rtsp did not work well in gpac,   I am not sure why 
/opt/git/gpac/bin/gcc/gpac -i rtsp://10.140.200.131:554/live/abc -o arch.mp4
[RTP] Request Timeout for command PLAY after 3000 ms
[RTSP] Error processing user command Network Unreachable
[RTP] UDP Timeout after 10000 ms on stream 1, retrying using TCP
[RTSP] Invalid sequence number - got 8 but expected 9
[RTSP] Error processing event PLAY: Internal Service Error
[RTSP] Invalid sequence number - got 9 but expected 10
[RTSP] Error processing event PLAY: Internal Service Error

**Comment by jeanlf** [comment]
We had a bug loading variant playlists directly indeed, should now be fixed. Can you cross-check ?

Regarding the RTSP, what is your source ?

**Comment by fastfading** [comment]
not fixed for this    two "abc" prefix ,    I used newest build  3 days ago

**Comment by jeanlf** [comment]
could you give it another try ?

**Comment by jeanlf** [comment]
closing as working here, reopen if needed
