### ISSUE TITLE
[DASH] MPD@maxSegmentDuration is missing while using DASH-AVC/264 live profile.

### ISSUE THREAD

**Issue by vladimir-kazakov** [gpac/gpac#25]
Hi!

While using MP4Box (GPAC rev 5572), I noticed that the MPD@maxSegmentDuration attribute is missing when the DASH-AVC/264 live profile is used. According to DASH-AVC/264 Interoperability Points v2.0, this attribute is mandatory (3.2.2, page 2, lines 25 and 31) - "If the MPD@profiles attribute includes "urn:mpeg: dash:profile:isoff-live:2011", then the attribute MPD@maxSegmentDuration shall be present".

**Comment by jeanlf** [comment]
Indeed, but this might take some time to fix as it implies a rearchitecture of the code ...

**Comment by jeanlf** [comment]
This should now be fixed thanks for the report

**Comment by vladimir-kazakov** [comment]
@jeanlf, I tried in GPAC version 0.5.2-DEV-rev87-ga51f89f-master, but this attribute is still missing. I used these files: http://1drv.ms/1zaXrZZ

**Comment by jeanlf** [comment]
retested with your files, here's the MPD header:

<?xml version="1.0"?>

<MPD xmlns="urn:mpeg:dash:schema:mpd:2011" minBufferTime="PT1.500000S" type="static" mediaPresentationDuration="PT0H0M52.21S" maxSegmentDuration="PT0H0M4.00S" profiles="urn:mpeg:dash:profile:isoff-live:2011, http://dashif.org/guildelines/dash264">

...
</MPD>

**Comment by vladimir-kazakov** [comment]
@jeanlf, I'm not sure what you were trying to say, but here's what I get:

```xml
<MPD xmlns="urn:mpeg:dash:schema:mpd:2011" minBufferTime="PT1.500000S" type="static" mediaPresentationDuration="PT0H0M52.21S" profiles="urn:mpeg:dash:profile:isoff-live:2011, http://dashif.org/guildelines/dash264">
```

So, as you can see, the MPD element doesn't have the "maxSegmentDuration" attribute.

The command I was using is:

```
mp4box.exe -dash 4000 -frag 4000 -rap -frag-rap -profile "dashavc264:live" -segment-name %s- "360p-700k-baseline30.mp4" "720p-1300k-high31.mp4" "1080p-2600k-high40.mp4" "audio-256k.m4a" -out "sintel.mpd"
```

**Comment by jeanlf** [comment]
I'm using this command with the same files, here's the mpd element

<?xml version="1.0"?>

<MPD xmlns="urn:mpeg:dash:schema:mpd:2011" minBufferTime="PT1.500000S" type="static" mediaPresentationDuration="PT0H0M52.21S" maxSegmentDuration="PT0H0M4.00S" profiles="urn:mpeg:dash:profile:isoff-live:2011, http://dashif.org/guildelines/dash264">

...
</MPD>

not sure you have the latest version, could you re-check ?

**Comment by vladimir-kazakov** [comment]
@jeanlf, I checked the version by using `mp4box.exe -version`, and got "GPAC version 0.5.2-DEV-rev87-ga51f89f-master". I installed it by using the "gpac-0.5.2-DEV-rev87-ga51f89f-master-x64.exe". That's the latest one on the web-site: http://gpac.wp.mines-telecom.fr/downloads/gpac-nightly-builds/.

Also, I don't see MPD elements in your comments. I see the XML declaration, and then 3 dots "...". Here's the screenshot: http://1drv.ms/1AUILSJ. Maybe GitHub escapes it :). Could you put it in the code block? (https://guides.github.com/features/mastering-markdown/)

**Comment by vladimir-kazakov** [comment]
@jeanlf, got it working in GPAC version 0.5.2-DEV-rev96-gfc92dbc-master. Thanks!
