### ISSUE TITLE
Dolby Vision signalling updates

### ISSUE THREAD

**Issue by rbouqueau** [gpac/gpac#2782]
It seems that we may not up to date with the latest [version 2.3](https://dolby.my.salesforce.com/sfc/p/#700000009YuG/a/4u000000l6FV/TqYPD0f0c3Zm40JJrFKFn1m29QdUxuVB.U_GzZzbXgE).

What I understand:
- For mixed DV and non-DV DASH representations, the codec value should be ```hev1```, optional codec should be ```dvhe```, and optional brands should be ```cdm4``` (for HDR10+) and ```db1p``` (for Dolby Vision 8.1).
  - See Table 1 for the DV brands depending on the CCID.
- For backward-compatibility, ```AdaptationSet@scte214:supplementalCodecs``` and
```AdaptationSet@scte214:supplementalProfiles``` to include Dolby Vision codes string and compatibility
brands.

Example:
```
mimeType="video/mp4" codecs="hev1.2.4.L153.B0"
scte214:supplementalCodecs="dvh1.08.09" scte214:supplementalProfiles="db1p"
```

Other namespace to be set: ```xmlns:scte214="urn:scte:dash:scte214-extensions"```

Some ```EssentialProperty``` *should* be present as well:
```
<AdaptationSet segmentAlignment="true"
subsegmentAlignment="true" subsegmentStartsWithSAP="1" >
  <EssentialProperty schemeIdUri="urn:mpeg:mpegB:cicp:MatrixCoefficients" value="9"/>
  <EssentialProperty schemeIdUri="urn:mpeg:mpegB:cicp:ColourPrimaries" value="9"/>
  <EssentialProperty schemeIdUri="urn:mpeg:mpegB:cicp:TransferCharacteristics” value="16"/>
  <Representation id="1" mimeType="video/mp4" codecs="hev1.2.4.L153.B0" scte214:supplementalCodecs= "dvh1.08.09" scte214:supplementalProfiles="db1p" segmentProfiles="chd1" width="3840" height="2160" frameRate="60000/1001" sar="1:1" startWithSAP="1" bandwidth="18667200" >
    <BaseURL>Dolby_visioin_p81.mp4</BaseURL>
    <SegmentBase indexRangeExact="true" indexRange="1009-1388">
      <Initialization range="0-1008"/>
    </SegmentBase>
  </Representation>
</AdaptationSet>
```

With some Dolby Atmos:
```
<?xml version="1.0"?>
<MPD xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"xmlns:dolby="http://www.dolby.com/ns/online/DASH" xmlns="urn:mpeg:dash:schema:mpd:2011" xsi:schemaLocation="urn:mpeg:dash:schema:mpd:2011" type="static" mediaPresentationDuration="PT0H1M2.550S" minBufferTime="PT1.2S" profiles="urn:mpeg:dash:profile:isoff-on-demand:2011">
  <BaseURL>./</BaseURL>
  <Period>
    <!-- Video -->
    <AdaptationSet mimeType="video/mp4" codecs="dvhe.05.07" subsegmentAlignment="true" subsegmentStartsWithSAP="1">
      <Representation id="1" bandwidth="17677192" width="3840" height="2160" frameRate="30000/1001">
        <BaseURL>profile5.mp4</BaseURL>
        <SegmentBase indexRange="812-1095">
          <Initialization range="0-811"/>
        </SegmentBase>
      </Representation>
    </AdaptationSet>
    <!-- Audio -->
    <AdaptationSet mimeType="audio/mp4" codecs="ec-3" lang="und" subsegmentAlignment="true" subsegmentStartsWithSAP="1">
      <Representation id="2" bandwidth="640000">
        <AudioChannelConfiguration schemeIdUri="tag:dolby.com,2014:dash:audio_channel_configuration:2011" value="F801"/>
        <SupplementalProperty schemeIdUri="tag:dolby.com,2018:dash:EC3_ExtensionType:2018" value="JOC"/>
        <SupplementalProperty schemeIdUri="tag:dolby.com,2018:dash:EC3_ExtensionComplexityIndex:2018" value="16"/>
        <BaseURL>audio.mp4</BaseURL>
        <SegmentBase indexRange="652-875">
          <Initialization range="0-651"/>
        </SegmentBase>
      </Representation>
    </AdaptationSet>
  </Period>
</MPD>
```

**Comment by jeanlf** [comment]
I think this was fixed no ?

**Comment by rbouqueau** [comment]
AFAIU we still don't generate `db1p`. CC @MingxinChen any opinion on this?

**Comment by MingxinChen** [comment]
Hi @rbouqueau, setting `db1p` as a supplemental profile in DASH has been fixed in https://github.com/gpac/gpac/pull/3431.

**Comment by rbouqueau** [comment]
Thanks @MingxinChen . Closing this one then.
