### ISSUE TITLE
dashcast with codec copy

### ISSUE THREAD

**Issue by luisloros** [gpac/gpac#443]
Hello,

I am trying to use dashcast to transform a live multicast stream into a MPEG-DASH stream without any transcoding. I though it would be easy with the copy option from FFMPEG. But apparently it is not mapped to dashcast therefore I get this error:
```
Output video codec copy not found
Cannot open output video stream.
```

Here is my command line 
```
dashcast.exe -av "udp://@238.4.4.4:5000?fifo_size=10000" -seg-dur 2000 -out "d:\temp" -conf dashcast.conf
```
and conf file
```
[v1] 
type=video 
codec=copy 
[a1] 
type=audio 
codec=copy
```

Can you help me with this issue?

Thank you,
Luis

**Comment by rbouqueau** [comment]
Dashcast re-encodes.

We have a new modular platform called Signals (https://github.com/gpac/Signals) and that would be a good test. What would you like to do exactly? Take a udp-in, remux&dash it live? Which player?

**Comment by luisloros** [comment]
Yes, exactly, I want to take a udp-in, remux and dash-it live. Currently I am testing it on shaka player, later I want to try with HbbTV (but still figuring how to do it...)

**Comment by rbouqueau** [comment]
Thanks for the feedback. FYI I didn't see you edit about the build failure because github doesn't send a new modification. Don't hesitate to make a new message in this case!

**Comment by rbouqueau** [comment]
Signals updated.

> Hunk #1 FAILED at 19.

Fixed, thanks for reporting.

> Moreover some links in the zenbuild are not working. Here is the list of the changes I made so far:
x264 -> https://git.videolan.org/git/x264.git
rtmp -> https://github.com/mirror/rtmpdump
ffmpeg -> https://github.com/FFmpeg/FFmpeg
libjpeg-turbo -> http://svn.code.sf.net/p/libjpeg-turbo/code/branches/1.3.x/
xproto -> http://anongit.freedesktop.org/git/xorg/proto/xproto.git/

Is there any reason to favor http over the git protocol? http is more reliable but is also slower

Now I'm going to solve the few things needed to build your tool.

**Comment by luisloros** [comment]
Hi again, try to recompile it but due to the `gcc -Werror` flag, the coimpilation stopped. I removed the flag but the compilation still failed. There are a lot of errors in the `src/lib_media/stream/mpeg_dash.cpp` file, more specifically:
`error: ‘variables_name’ was not declared in this scope`
Here is the log file: [compil.txt](https://github.com/gpac/gpac/files/184329/compil.txt)

**Comment by rbouqueau** [comment]
I know. I will ping you back here when it is ready.

Also I'd be happy to know about this:
> Is there any reason to favor http over the git protocol? http is more reliable but is also slower

**Comment by luisloros** [comment]
Ok, thank you ;)

As for this:
> Is there any reason to favor http over the git protocol? http is more reliable but is also slower

I am having issues with some links with the git protocol...

> x264 -> https://git.videolan.org/git/x264.git

Works with git protocol.
> rtmp -> https://github.com/mirror/rtmpdump

Works with git protocol.
> ffmpeg -> https://github.com/FFmpeg/FFmpeg

Works with git protocol.
> xproto -> http://anongit.freedesktop.org/git/xorg/proto/xproto.git/

Can get it to work with git protocol, I get a certificate error.

**Comment by rbouqueau** [comment]
For changing the sources, feel free to make a pull request on the zenbuild repo, see https://github.com/gpac/zenbuild/issues/23. Otherwise I'll make it when I find time.

For the dashcast stuff, do you have a sample input stream? A FFmpeg command-line would be great. Many thanks for your help and inputs.

**Comment by luisloros** [comment]
I'll try to do a pull request next week.

Meanwhile here is the FFmpeg command-line I am using:
ffmpeg -i media_in.mp4 -vf scale=1280:720 -acodec aac -ab 192k-ac 2 -c:v libx265 -preset ultrafast -x265-params bitrate=4000:vbv-maxrate4000:vbv-bufsize=4000:no-open-gop=1:keyint=50:min-keyint=50:no-scenecut=1:ref=4:fps=25 media_out.mp4

**Comment by rbouqueau** [comment]
Thanks. I made some good progress in the meantime. Coming back to you soon.

**Comment by rbouqueau** [comment]
I've just push a new release of Signals. I could test you use case by transcoding a source with your command-line, then streaming it with:
```
ffmpeg -re -i source.mp4 -vcodec copy -f mpegts udp://127.0.0.1:10000?pkt_size=1316
```

Dashcastx: ```-l -s 1000 udp://127.0.0.1:10000```

If you want to test it and talk about it, let's close the issue and move to the Signals github. Thanks

**Comment by luisloros** [comment]
Ok, I will test and report back on the Signals github.

Thank you for the help!
