### ISSUE TITLE
MP4box Alternate Groups

### ISSUE THREAD

**Issue by 4getit** [gpac/gpac#444]
Since iTunes is kinda picky, I'm trying to move audio tracks into the same group.

The -group-add options is giving me issues though.

When I try to move audio track 3 to the same group as track 2, I assume I need to do something like: ../MP4Box -group-add -refTrack=2:trackID=3 video.m4v
However, this gives: 'Error: Bad Parameter'.

MP4Box -group-single video.m4v
...exits without doing anything

MP4Box -group-clean video.m4v
...gives a 'Segmentation fault: 11'

Using 0.6.0-DEV-rev16-gf9a7e0b-master

**Comment by jeanlf** [comment]
this should have been fixed in 0.6.1 I believe, and for sure on git

**Comment by 4getit** [comment]
I'm afraid I'm still getting the same "Error: Bad Parameter" message with
MP4Box - GPAC version 0.6.2-DEV-rev104-g29ffbde-master

**Comment by 4getit** [comment]
As additional info, this seems to work once:
MP4Box testfile.m4v -group-add trackID=1:trackID=2

It will create a new group with 1 & 2 in it.
I think that has to do with refTrack not being set and since it's the first track, it creates a new one.
"If not set, the track will belong to the same group as the previous trackID specified.
If 0 or no previous track specified, a new alternate group will be created"

Running the same command a second time doesn't not work. (Bad parameter)

For iTunes, I'm trying to move the audio and subtitle tracks in their own different groups.

**Comment by nguyen-viet-thanh-trung** [comment]
Hi,
Could you please share your test file so that we can reproduce ?  https://www.mediafire.com/filedrop/filedrop_hosted.php?drop=eec9e058a9486fe4e99c33021481d9e1826ca9dbc242a6cfaab0fe95da5e5d95

**Comment by 4getit** [comment]
I've uploaded a test file with two audio streams and a bunch of subtitles.
For iTunes, the second audio stream must be disabled. MP4Box allows me to do that.
All subtitles need to be in the same but separate -group. I'm unable to get that done with -add-group or any of the other group -related options.  
Thanks!

**Comment by nguyen-viet-thanh-trung** [comment]
It should be fixed now, could you please retry ? In fact, for the first time you should use: MP4Box testfile.m4v -group-add trackID=1:trackID=2, then for the second time you use: MP4Box testfile.m4v -group-add refTrack=1:trackID=2

**Comment by 4getit** [comment]
It works now! Excellent job.
Thank you!
