### ISSUE TITLE
No .mpd file is generated

### ISSUE THREAD

**Issue by irrz** [gpac/gpac#621]
Hello there,

I am trying to make a live streaming using x265

I sat up all the system on Linux Ubuntu, and when I start streaming, i find that the output folder doesn't have an .mpd file so I cannot get this live streaming at the client side

the command I use is:
acer@acer-Aspire-4741:~/dash/gpac-master/applications/dashcast$ DashCast -vf video4linux2 -vres 1280x800 -vfr 30 -v4l2f yuyv -v /dev/video0 -live  -out /opt/lampp/htdocs/dash -conf dashcast.conf -seg-dur 1000^C

**Comment by Victordmdb** [comment]
Resolved here: https://github.com/gpac/gpac/issues/538

**Comment by irrz** [comment]
Thank you Victor for the referal, however, it still the same no .mpd file

**Comment by Victordmdb** [comment]
You might be getting some other errors, please share the output of your command.

**Comment by irrz** [comment]
Thanks again for the prompt reply 
and please find out the attached file

![screenshot from 2016-09-06 04 01 32](https://cloud.githubusercontent.com/assets/16091677/18260557/c2ab1d14-73e6-11e6-9949-c501d624d0b9.png)

**Comment by Victordmdb** [comment]
As in the  CLI output

**Comment by irrz** [comment]
Sorry I didn't catch what do you mean

**Comment by Victordmdb** [comment]
When you type your command into terminal on ubuntu, there are lines of output which should appear, in terminal

**Comment by irrz** [comment]
Here you go pal 

![screenshot from 2016-09-06 04 17 35](https://cloud.githubusercontent.com/assets/16091677/18260781/fa52a9d8-73e8-11e6-9fb7-b645136c4fa6.png)
![screenshot from 2016-09-06 04 17 44](https://cloud.githubusercontent.com/assets/16091677/18260782/fa558c0c-73e8-11e6-8db8-cb53a75d1816.png)

**Comment by Victordmdb** [comment]
So you removed the line [described in](https://github.com/gpac/gpac/issues/538)?

Go into 'gpac/applications/dashcast/controler.c'
Go into the 'dc_write_mpd function', comment out this line:
if (!audio_data_conf) return;
Recompile file with gcc or just 'make' the whole project again

**Comment by irrz** [comment]
Thank you very much Victor,
It works now fine, as I believe that when I comment out that line, I only did 'make' on "dashcast folder".

Again, Thank you very much
