### ISSUE TITLE
MP4box split by size: 4 Gb limit

### ISSUE THREAD

**Issue by svintuss** [gpac/gpac#680]
When trying to split a file into segments by size mp4box won't generate files larger than 4 Gb. In the following example:

mp4box -splits 4194303  input_file.mp4

4194303 is the highest split size in kilobytes that is treated correctly. After 4194304 it starts generating files of the size equal to remainder after division n/4194303.

Tested on OS X 10.12.1:
.$ MP4Box -version
MP4Box - GPAC version 0.6.2-DEV-rev1057-g7d57811-master
GPAC Copyright (c) Telecom ParisTech 2000-2012
GPAC Configuration: --extra-cflags=-Wno-deprecated
Features: GPAC_64_BITS GPAC_HAS_SSL GPAC_HAS_SPIDERMONKEY GPAC_HAS_JPEG GPAC_HAS_PNG

**Comment by rbouqueau** [comment]
Thanks for reporting. I may have found the culprit:
```
u32 split_size_kb;
[...]
split_size_kb *= 1024;
```

I need to be able to reproduce to fix properly. Please give me some time.

**Comment by hriad** [comment]
Any update on this issue?

**Comment by rbouqueau** [comment]
I pushed a commit but couldn't test. Could you test please?

**Comment by jeanlf** [comment]
reopen if patch not working

**Comment by MisterX2000** [comment]
The Problem still persists. I'm using gpac-0.7.2-DEV-rev778-gf4c215e8-master-x64 and I want to split a large file in to 5 GB parts, but it just goes through the file completely and copies it.

**Comment by MisterX2000** [comment]
I've tested it with a 12GB file and split it in 5GB and 6GB parts. It now works flawlessly.
Thx.
