### ISSUE TITLE
Playback of CENC encrypted DASH chunks in version 0.7.1

### ISSUE THREAD

**Issue by aaani** [gpac/gpac#832]
1. Encrypt input media -
```
~ Mp4box -crypt /Users/ani/work/input/crypt.xml -out output/enc-sintel-1024-video.mp4 input/sintel-1024-video.mp4
```

2. Create DASH chunks of encrypted media -
```
~ Mp4box -dash 2000 -profile simple -mpd-refresh 4.0 -rap -segment-name dash_$RepresentationID$_$Number output/enc-sintel-1024-video.mp4 -out output/play.mpd 
```

Above workflow worked perfectly in `GPAC version 0.6.1-revrelease` but when I upgraded to `GPAC version 0.7.1-revrelease` encrypted DASH segments stopped working in my player (shaka player). 

Are there any known issues? I would greatly appreciate any kind of help. Thanks!

**Comment by ycinfinity** [comment]
Hi @aaani ,I'm trying to encrypt fmp4 with 'cbcs'. This is my drm_crypt.xml.
```
<?xml version="1.0" encoding="UTF-8"?>
<GPACDRM type="CENC AES-CBC Pattern">
<DRMInfo type="pssh" version="1">
<BS ID128="0x1077EFECC0B24D02ACE33C1E52E2FB4B"/>
<BS value="1" bits="32"/>
<BS ID128="0x279926496a7f5d25da69f2b3b2799a7f"/>
</DRMInfo>
<CrypTrack trackID="1" IsEncrypted="1" constant_IV_size="16" constant_IV="0x92dfe22e1cbd54651fce92cd54d34078" crypt_byte_block = "1" skip_byte_block = "9" saiSavedBox="senc">
<key KID="0x279926496a7f5d25da69f2b3b2799a7f" value="0x5172f0c47fb41ac5efad2d354d3db2be"/>
</CrypTrack>
</GPACDRM>
```

It can't work. Do you know what's wrong? Could you share your crypt.xml?

Thanks

**Comment by jeanlf** [comment]
Have you tried with the latest git. we fixed a bug in 0.7.1 regarding CENC which is probably what you experience - reopen if needed

**Comment by aaani** [comment]
I tried with `MP4Box - GPAC version 0.7.2-DEV-rev185-g0bc03b234-master` and this is still an issue. The error that I get during playback is [MEDIA_ERR_DECODE](https://developer.mozilla.org/en-US/docs/Web/API/MediaError/code#Media_error_code_constants), which probably indicates something unexpected happened during the encryption. Again, this isn't an issue with version 0.6.1.

Could you reopen the issue?

**Comment by rbouqueau** [comment]
Certainly but can you provide a sample so that we can reproduce please?

We have an anonymous dropbox if helpful: https://www.mediafire.com/filedrop/filedrop_hosted.php?drop=eec9e058a9486fe4e99c33021481d9e1826ca9dbc242a6cfaab0fe95da5e5d95

Many thanks

**Comment by jeanlf** [comment]
we should have fixed all CENC issues in 0.8.0 - please retry and reopen if needed
