### ISSUE TITLE
MP4Box drops 1st key frame when importing h264_nvenc encode

### ISSUE THREAD

**Issue by teamandro** [gpac/gpac#916]
I have a problem when importing a video stream encoded with h264_nvenc in h264 raw format. My system configuration:
- Windows 10 Pro 64 Bit (Version 1703)
- MP4Box version 0.7.2-DEV rev283
- All commands are executed via the cli

Please find video examples at the following urls.

Original video:
https://test.team-andro.eu/video/examples/ace2011.mov

540p encode h264 raw:
https://test.team-andro.eu/video/examples/ace2011_540p.264

The video encode has a frame rate of 29.970 with a key frame interval of 150 frames. This means: The first frame is a key frame, the 151st frame is a key frame and so on. The reason for that is to get a dash interval of 5,005 seconds.

After creating the h264 raw stream I import it with the help of MP4Box. Cli command:

MP4Box -add ace2011_540p.264#video:fps=29.97 -new ace2011_540p.mp4

This has always worked without any problems. The last version of MP4Box I've been using was 0.7.2-DEV rev34 from May 2017. Now I've updated MP4Box to 0.7.2-DEV rev283 and the behaviour is different. Please see the following examples.

File after import with 0.7.2-DEV rev34
https://test.team-andro.eu/video/examples/ace2011_540p-rev34.mp4

File after import with 0.7.2-DEV rev283
https://test.team-andro.eu/video/examples/ace2011_540p-rev283.mp4

If you analyze those videos with the help of ffprobe, you will see that the key frame at the beginning is missing in the version created with 0.7.2-DEV rev283. ffprobe commands to create text files listing all frames:

ffprobe -i ace2011_540p-rev34.mp4 -show_frames > rev34.txt
ffprobe -i ace2011_540p-rev283.mp4 -show_frames > rev283.txt

Please see my examples at:
https://test.team-andro.eu/video/examples/rev34.txt
https://test.team-andro.eu/video/examples/rev283.txt

The problem becomes obvious when a dash stream is created based on such imports (with 0.7.2-DEV rev283). The missing key frame at the beginning leads to a big gap and the video won't play. Please see the following examples:

Dash stream created with 0.7.2-DEV rev34
https://shaka-player-demo.appspot.com/demo/#asset=https://test.team-andro.eu/video/ace2011-rev34/mp4_1.mpd;lang=en-US
-> plays fine

Dash stream created with 0.7.2-DEV rev283
https://shaka-player-demo.appspot.com/demo/#asset=https://test.team-andro.eu/video/ace2011-rev283/mp4_1.mpd;lang=en-US
-> doesn't start

The problem doesn't occur in conjunction with libx264 encodes.

**Comment by rbouqueau** [comment]
@cconcolato Wasn't this fixed by e2aab1fd95647a4a24da863ff1074d26c11fe11d?
@teamandro Could you retry with the latest release please?

**Comment by cconcolato** [comment]
@rbouqueau I don't think my fix is related. My fix is about input containing only 1 frame.

**Comment by teamandro** [comment]
Thank you very much for your comments. I've just tested version 0.7.2-DEV rev291.
Unfortunately the problem persists. The result seems to be the same as with version  0.7.2-DEV rev283.

**Comment by teamandro** [comment]
Just tested again with 0.7.2-DEV rev626. The problem has disappeared :-)
