### ISSUE TITLE
'lmsg' in STATIC MPDs with LIVE profiles.

### ISSUE THREAD

**Issue by richardbushell** [gpac/gpac#93]
Hi Jean, I see you closed issue #78, but there is definitely some confusion here.

I refer to TYPE="STATIC" MPDs (NOT Type="Dynamic") using SEGMENT TEMPLATE under a LIVE profile. These should these have 'lmsg' brand. They are STATIC so no MPD update can add any further segments. We KNOW that this is the last segment!

The DASH Validator complains that they should be present as brand in last segment.

**Comment by jeanlf** [comment]
Could you check last version ? The issue seems to appear when segment duration is not well aligned with gop pattern, should now be fixed

**Comment by richardbushell** [comment]
No, still the same. This is the conformance message:
Brand 'lmsg' not found as a compatible brand for the last segment (number 8); violates Section 3.2.3. of Interoperability Point DASH264: If the MPD@type is equal to "dynamic" or if it includes MPD@profile attribute includes "urn:mpeg:dash:profile:isoff-live:2011", then: if the Media Segment is the last Media Segment in the Representation, this Media Segment shall carry the 'lmsg' compatibility brand.

Just for clarification have you made the changes for TYPE="STATIC" when LIVE profile is used. My MPD is NOT type="dynamic".

The MPD is here:
http://living.tv/mob/ibeani_i4_mcstdlow_8000.mpd

**Comment by jeanlf** [comment]
could you post the source mp4 somewhere ?

**Comment by richardbushell** [comment]
Source file is now uploaded here:
http://living.tv/mob/ibeani_i4_mcstdlow.mp4

I haven't looked at your source code at all, but in programming terms I think we need a statement something like:
IF (mpd_type == STATIC) && (mpd_profile == LIVE) && (IsLastSegment) THEN brand = 'lmsg'
(obviously I haven't referenced your real code, but hopefully you know what I mean by the example)

Our MPD s STATIC, not DYNAMIC.

**Comment by jeanlf** [comment]
tried here with live profile and 1s and 5s segment duration , lmsg is present in the last segment. Can you give me the command line used ?

**Comment by richardbushell** [comment]
MP4Box -dash 8000 -frag 8000 -rap -frag-rap -no-frags-default -profile dashavc264:live -new -segment-name %%s -url-template -out "out\test.mpd" input_video.m4v input_audio.m4a

**Comment by jeanlf** [comment]
works fine with the file you gave , last segment has lmsg listed

**Comment by richardbushell** [comment]
Conformance says not, goto:
http://dashif.org/conformance.html
using MPD:
http://living.tv/mob/ibeani_i4_mcstdlow_8000.mpd
Reports:
### Brand 'lmsg' not found as a compatible brand for the last segment (number 8); violates Section 3.2.3. of Interoperability Point DASH264: If the MPD@type is equal to "dynamic" or if it includes MPD@profile attribute in-cludes "urn:mpeg:dash:profile:isoff-live:2011", then: if the Media Segment is the last Media Segment in the Representation, this Me-dia Segment shall carry the 'lmsg' compatibility brand.
What is going on here?
Does your MPD say type="static"? Please can you send me the MPD you generated from the same source file so I can compare that.

**Comment by richardbushell** [comment]
Could it be a bug in the Conformance tool??? Baffled...

**Comment by richardbushell** [comment]
Hi Jean

I have reported the issue on DASH-IF github here:

https://github.com/Dash-Industry-Forum/Conformance-Software/issues/54

I think this must be a false positive. Apologies if it is their error, I will let you know.

**Comment by richardbushell** [comment]
Hi Jean
DASH-IF have fixed this issue in their DASH Conformance Validator.
Apologies again if you had to review code that was working correctly your end!
Please close this issue.
